// gpt-worker relay.
//
// One Worker, many workspaces: each workspace gets its own Durable Object
// instance (keyed by workspace_id), so each has an independent queue, its
// own 3 tokens, and its own /link WebSocket — starting the bridge for one
// workspace never evicts another's connection.
//
//   /mcp/<hub_gpt_token>               Shared ChatGPT-facing MCP endpoint. It exposes
//                                       registered workspaces as an explicit tool argument.
//   /mcp/<workspace_id>/<gpt_token>    Legacy per-workspace MCP endpoint (kept for migration).
//   /local/<workspace_id>/<cli_token> CLI-facing postbox API (enqueue / poll / ack / status).
//   /link/<workspace_id>/<link_token> WebSocket reverse-connection from the local bridge process.
//   /admin/<ADMIN_TOKEN>              Provision a new workspace_id, or migrate an old
//                                     single-tenant deployment's tokens into one. Never
//                                     appears in a per-workspace URL; set once machine-wide.
//
// workspace_id is a routing key, not a secret — it just selects which Durable
// Object instance handles the request. The actual gpt/link/cli tokens are
// generated by /admin and stored *inside* that instance's own SQLite (a
// `secrets` table), which is why token validation now happens inside the
// Durable Object rather than here at the top level: only that instance knows
// its own tokens.
//
// The Durable Object (BridgeDO) is the only stateful piece: it holds the message
// queue (SQLite) and the live WebSocket link to the local bridge, using the
// WebSocket Hibernation API so it costs nothing while idle.
//
// See ~/.agents/skills/gpt-worker/SKILL.md for the operating protocol and
// ~/.agents/skills/gpt-worker/reference/protocol.md for message formats.

import TOOLS from "./tools.json" with { type: "json" };

const HUB_TOOLS = [
  {
    name: "list_workspaces",
    title: "List workspaces",
    description: "List every workspace registered with this shared gpt-worker connector. Choose one workspace_id, then pass it to every other gpt-worker tool call.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  },
  ...TOOLS.tools.map((tool) => ({
    ...tool,
    description: `${tool.description} In the shared connector, pass workspace_id from list_workspaces for this call.`,
    inputSchema: {
      ...tool.inputSchema,
      properties: {
        ...tool.inputSchema.properties,
        workspace_id: { type: "string", description: "Workspace ID returned by list_workspaces." },
      },
      required: [...new Set([...(tool.inputSchema.required || []), "workspace_id"])],
    },
  })),
];

const PROTOCOL_VERSIONS = new Set(["2025-06-18", "2025-03-26"]);
const DEFAULT_PROTOCOL_VERSION = "2025-03-26";
const ALLOWED_ORIGINS = new Set(["https://chatgpt.com", "https://chat.openai.com"]);
const RPC_TIMEOUT_MS = 20_000; // local WS round-trip budget
const POLL_MAX_MS = 20_000; // CLI long-poll budget
const LEASE_MS = 120_000; // next_task lease before it can be re-claimed
const MAX_BODY_BYTES = 16 * 1024; // the `body` text field inside a message
const MAX_REQUEST_BYTES = 32 * 1024; // the whole JSON-RPC/CLI envelope around it
const RETENTION_MS = 7 * 24 * 60 * 60 * 1000;
const ALARM_INTERVAL_MS = 24 * 60 * 60 * 1000;
const ACTIVE_WINDOW_MS = 60 * 60 * 1000;
const WORKSPACE_ID_RE = /^[0-9a-f]{16}$/;
const HUB_DO_NAME = "gpt-worker-hub";
// "default" is the one pre-existing exception: the original single-tenant
// deployment's Durable Object was idFromName("default") verbatim, so the
// migration path (see BridgeDO.migrateDefault) must be able to address that
// exact same instance under the new multi-tenant routing. Every workspace
// provisioned from here on gets a fresh 16-hex-char id instead.
function isValidWorkspaceId(id) {
  return id === "default" || WORKSPACE_ID_RE.test(id);
}

// ---------------------------------------------------------------------------
// Top-level Worker: validate path shape, then hand off to the right
// per-workspace Durable Object. Per-workspace token validation happens
// *inside* the Durable Object (see BridgeDO.checkToken) — this layer only
// ever sees workspace_id (not secret) and, for /admin, ADMIN_TOKEN.
// ---------------------------------------------------------------------------

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const parts = url.pathname.split("/").filter(Boolean);

    if (parts.length === 2 && parts[0] === "admin") {
      return handleAdminRoute(request, env, parts[1]);
    }

    // The shared connector has one stable URL, independent of any individual
    // workspace. It is deliberately a different path shape from the legacy
    // per-workspace endpoint, so existing connectors remain usable during
    // migration.
    if (parts.length === 2 && parts[0] === "mcp") {
      if (!checkOrigin(request)) return new Response("forbidden", { status: 403 });
      const hub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(HUB_DO_NAME));
      const forwardUrl = new URL(request.url);
      forwardUrl.pathname = `/hub-mcp/${parts[1]}`;
      return hub.fetch(new Request(forwardUrl, request));
    }

    if (parts.length !== 3) return new Response("not found", { status: 404 });
    const [route, workspaceId, token] = parts;
    if (!["mcp", "link", "local"].includes(route)) return new Response("not found", { status: 404 });
    if (!isValidWorkspaceId(workspaceId)) return new Response("not found", { status: 404 });

    if (!checkOrigin(request)) {
      return new Response("forbidden", { status: 403 });
    }

    const doId = env.BRIDGE_DO.idFromName(workspaceId);
    const stub = env.BRIDGE_DO.get(doId);

    // Forward as /<route>/<token> — the Durable Object still needs the
    // token (to check it against its own stored secret), just not the
    // workspace_id (that already *is* which instance it is).
    const forwardUrl = new URL(request.url);
    forwardUrl.pathname = `/${route}/${token}`;
    return stub.fetch(new Request(forwardUrl, request));
  },
};

async function handleAdminRoute(request, env, adminToken) {
  if (!env.ADMIN_TOKEN || !constantTimeEqual(adminToken, env.ADMIN_TOKEN)) {
    return new Response("not found", { status: 404 });
  }
  if (!checkOrigin(request)) return new Response("forbidden", { status: 403 });
  if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });

  // Peek at workspace_id (size-capped, same as any other body) from a clone
  // so the real body — still fully intact — can be forwarded to the target
  // Durable Object, which reads it again itself.
  const peeked = await readJsonWithLimit(request.clone(), MAX_REQUEST_BYTES);
  if (peeked.tooLarge) return new Response("payload too large", { status: 413 });
  if (peeked.parseError || !peeked.value) return new Response("bad request", { status: 400 });
  if (["provision_hub", "register_workspace", "unregister_workspace", "rotate_hub"].includes(peeked.value.op)) {
    const hub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(HUB_DO_NAME));
    const forwardUrl = new URL(request.url);
    forwardUrl.pathname = "/admin";
    return hub.fetch(new Request(forwardUrl, request));
  }

  const workspaceId = peeked.value.workspace_id;
  if (typeof workspaceId !== "string" || !isValidWorkspaceId(workspaceId)) {
    return new Response("bad request", { status: 400 });
  }

  const doId = env.BRIDGE_DO.idFromName(workspaceId);
  const stub = env.BRIDGE_DO.get(doId);
  const forwardUrl = new URL(request.url);
  forwardUrl.pathname = "/admin";
  return stub.fetch(new Request(forwardUrl, request));
}

function randomHex(bytes) {
  const arr = new Uint8Array(bytes);
  crypto.getRandomValues(arr);
  return [...arr].map((b) => b.toString(16).padStart(2, "0")).join("");
}

function constantTimeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function checkOrigin(request) {
  const origin = request.headers.get("origin");
  if (!origin) return true; // server-to-server calls (ChatGPT backend, curl, CLI) send none
  return ALLOWED_ORIGINS.has(origin);
}

function checkProtocolVersion(request) {
  const v = request.headers.get("mcp-protocol-version");
  if (!v) return DEFAULT_PROTOCOL_VERSION;
  return PROTOCOL_VERSIONS.has(v) ? v : null;
}

function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...headers },
  });
}

function rpcError(id, code, message) {
  return json({ jsonrpc: "2.0", id: id ?? null, error: { code, message } });
}

function toolOk(data) {
  return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: data };
}

function toolError(code, message) {
  const data = { error: code, message };
  return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: data, isError: true };
}

function byteLength(str) {
  return new TextEncoder().encode(str).length;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Reads and JSON-parses a request body while enforcing maxBytes *during*
 *  the read — not just by checking Content-Length (absent for chunked
 *  requests, and not to be trusted anyway) and not just by inspecting a
 *  field's length after the whole body has already been buffered and
 *  parsed. Returns { tooLarge } if the cap is hit, aborting the read early;
 *  otherwise { value } (parsed JSON) or { parseError: true }. */
async function readJsonWithLimit(request, maxBytes) {
  const contentLength = request.headers.get("content-length");
  if (contentLength && Number(contentLength) > maxBytes) return { tooLarge: true };

  const reader = request.body ? request.body.getReader() : null;
  if (!reader) return { value: undefined };

  let total = 0;
  const chunks = [];
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    total += value.byteLength;
    if (total > maxBytes) {
      try {
        await reader.cancel();
      } catch {
        /* best-effort */
      }
      return { tooLarge: true };
    }
    chunks.push(value);
  }

  const buf = new Uint8Array(total);
  let offset = 0;
  for (const c of chunks) {
    buf.set(c, offset);
    offset += c.byteLength;
  }
  try {
    return { value: JSON.parse(new TextDecoder().decode(buf)) };
  } catch {
    return { parseError: true };
  }
}

// ---------------------------------------------------------------------------
// Durable Object: queue + WebSocket relay.
// ---------------------------------------------------------------------------

export class BridgeDO {
  constructor(ctx, env) {
    this.ctx = ctx;
    this.env = env;
    this.sql = ctx.storage.sql;
    this.pending = new Map(); // rid -> { resolve, timer }
    this.rateBuckets = new Map(); // key -> number[] (best-effort; resets on hibernation restart)

    this.sql.exec(`
      CREATE TABLE IF NOT EXISTS msgs (
        message_id  TEXT PRIMARY KEY,
        dir         TEXT NOT NULL,       -- 'to_gpt' | 'to_local'
        task_id     TEXT NOT NULL,
        iteration   INTEGER NOT NULL,
        kind        TEXT NOT NULL,       -- INIT/EXECUTED/PLAN/DONE/BLOCKED
        body        TEXT NOT NULL,
        state       TEXT NOT NULL,       -- 'pending' | 'leased' | 'acked'
        lease_until INTEGER,
        created_at  INTEGER NOT NULL
      )
    `);
    this.sql.exec(`CREATE INDEX IF NOT EXISTS idx_q ON msgs(dir, state, created_at)`);

    // Workflow state is deliberately separate from the delivery queue. Queue
    // rows are short-lived transport records; tasks are the durable source of
    // truth that a new local bridge uses to resume after a restart.
    this.sql.exec(`
      CREATE TABLE IF NOT EXISTS tasks (
        task_id          TEXT PRIMARY KEY,
        goal             TEXT NOT NULL,
        iteration        INTEGER NOT NULL,
        protocol_state   TEXT NOT NULL,
        waiting_for      TEXT NOT NULL,
        task_started_at  INTEGER NOT NULL,
        updated_at       INTEGER NOT NULL,
        terminal_summary TEXT
      )
    `);
    this.sql.exec(`CREATE INDEX IF NOT EXISTS idx_tasks_active ON tasks(protocol_state, updated_at DESC)`);

    // Non-secret, Workspace-scoped preferences. Keeping these here avoids
    // using state.json as an accidental second task-state store. Secrets stay
    // in the dedicated secrets table above.
    this.sql.exec(`CREATE TABLE IF NOT EXISTS settings (k TEXT PRIMARY KEY, v TEXT NOT NULL)`);

    // This instance's own gpt/link/cli tokens (one workspace = one DO = one
    // row per key here). Set once via /admin's provision or migrate_default;
    // never a Worker Secret, since a Worker Secret is shared by every
    // workspace's DO instance and these must not be.
    this.sql.exec(`CREATE TABLE IF NOT EXISTS secrets (k TEXT PRIMARY KEY, v TEXT NOT NULL)`);

    // Used only by the dedicated hub Durable Object. Keeping the registry in
    // the same class makes it easy to evolve without another Worker binding;
    // individual workspace instances simply leave this table empty.
    this.sql.exec(`
      CREATE TABLE IF NOT EXISTS workspace_registry (
        workspace_id TEXT PRIMARY KEY,
        name         TEXT NOT NULL,
        registered_at INTEGER NOT NULL
      )
    `);

    ctx.blockConcurrencyWhile(async () => {
      const current = await ctx.storage.getAlarm();
      if (current === null) await ctx.storage.setAlarm(Date.now() + ALARM_INTERVAL_MS);
    });
  }

  async fetch(request) {
    const url = new URL(request.url);
    const parts = url.pathname.split("/").filter(Boolean);
    if (parts.length === 1 && parts[0] === "admin") return this.handleAdmin(request);
    if (parts.length === 1 && parts[0] === "hub") return this.handleHubRelay(request);
    if (parts.length !== 2) return new Response("not found", { status: 404 });
    const [route, token] = parts;
    if (route === "hub-mcp") return this.handleHubMcpRoute(request, token);
    if (route === "link") return this.handleLink(request, token);
    if (route === "mcp") return this.handleMcpRoute(request, token);
    if (route === "local") return this.handleLocalRoute(request, token);
    return new Response("not found", { status: 404 });
  }

  // ======================= secrets (per-workspace tokens) =======================

  getSecret(key) {
    const rows = this.sql.exec(`SELECT v FROM secrets WHERE k = ?`, key).toArray();
    return rows.length ? rows[0].v : null;
  }

  setSecret(key, value) {
    this.sql.exec(`INSERT OR REPLACE INTO secrets (k, v) VALUES (?, ?)`, key, value);
  }

  hasSecrets() {
    return this.sql.exec(`SELECT COUNT(*) AS n FROM secrets`).toArray()[0].n > 0;
  }

  checkToken(secretKey, token) {
    const stored = this.getSecret(secretKey);
    return !!stored && constantTimeEqual(token, stored);
  }

  // ======================= /admin : provisioning (this workspace's own DO) =======================

  async handleAdmin(request) {
    if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });
    const parsed = await readJsonWithLimit(request, MAX_REQUEST_BYTES);
    if (parsed.tooLarge) return new Response("payload too large", { status: 413 });
    if (parsed.parseError) return json({ error: "PARSE_ERROR" }, 400);
    const body = parsed.value || {};
    if (body.op === "provision_hub") return json(this.provisionHub());
    if (body.op === "register_workspace") return json(this.registerWorkspace(body));
    if (body.op === "unregister_workspace") return json(this.unregisterWorkspace(body));
    if (body.op === "rotate_hub") return json(this.rotateHubToken());
    if (body.op === "provision") return json(this.provision());
    if (body.op === "migrate_default") return json(this.migrateDefault(body));
    if (body.op === "rotate") return json(this.rotateSecret(body.key));
    if (body.op === "deprovision") return json(this.deprovision());
    return json({ error: "UNKNOWN_OP" }, 400);
  }

  /** Irreversibly wipes this workspace's tokens, queue, task state and settings — its Server URL
   *  and CLI/link tokens 404 immediately afterward, same as if it had never
   *  been provisioned. Used by `gpt-worker remove`. There is no "undo": a
   *  workspace_id can be re-provisioned later, but that starts a fresh
   *  queue with fresh tokens, not a restore of what was here. */
  deprovision() {
    this.sql.exec(`DELETE FROM secrets`);
    this.sql.exec(`DELETE FROM msgs`);
    this.sql.exec(`DELETE FROM tasks`);
    this.sql.exec(`DELETE FROM settings`);
    return { ok: true };
  }

  /** Replaces one of this workspace's 3 tokens with a fresh random value.
   *  Only the named key changes; the other two (and every queued message)
   *  are untouched. Requires the workspace to already be provisioned. */
  rotateSecret(key) {
    if (!["gpt_token", "link_token", "cli_token"].includes(key)) {
      return { error: "INVALID_ARGS", message: "key must be gpt_token, link_token, or cli_token" };
    }
    if (!this.hasSecrets()) return { error: "NOT_PROVISIONED" };
    const value = randomHex(32);
    this.setSecret(key, value);
    return { value };
  }

  /** Fresh workspace: generates all 3 tokens. Refuses if this workspace_id
   *  was already provisioned, so a routing collision (or a retried admin
   *  call) can never silently overwrite an existing workspace's tokens. */
  provision() {
    if (this.hasSecrets()) return { error: "ALREADY_PROVISIONED" };
    const gptToken = randomHex(32);
    const linkToken = randomHex(32);
    const cliToken = randomHex(32);
    this.setSecret("gpt_token", gptToken);
    this.setSecret("link_token", linkToken);
    this.setSecret("cli_token", cliToken);
    return { gptToken, linkToken, cliToken };
  }

  /** Creates the one token embedded in the single ChatGPT connector URL. */
  provisionHub() {
    const existing = this.getSecret("hub_gpt_token");
    if (existing) return { gptToken: existing, alreadyProvisioned: true };
    const gptToken = randomHex(32);
    this.setSecret("hub_gpt_token", gptToken);
    return { gptToken };
  }

  rotateHubToken() {
    if (!this.getSecret("hub_gpt_token")) return { error: "NOT_PROVISIONED" };
    const value = randomHex(32);
    this.setSecret("hub_gpt_token", value);
    return { value };
  }

  registerWorkspace({ workspace_id: workspaceId, name } = {}) {
    if (!isValidWorkspaceId(workspaceId) || typeof name !== "string" || !name.trim()) {
      return { error: "INVALID_ARGS" };
    }
    this.sql.exec(
      `INSERT OR REPLACE INTO workspace_registry (workspace_id, name, registered_at) VALUES (?, ?, ?)`,
      workspaceId,
      name.slice(0, 200),
      Date.now()
    );
    return { ok: true };
  }

  unregisterWorkspace({ workspace_id: workspaceId } = {}) {
    if (!isValidWorkspaceId(workspaceId)) return { error: "INVALID_ARGS" };
    this.sql.exec(`DELETE FROM workspace_registry WHERE workspace_id = ?`, workspaceId);
    return { ok: true };
  }

  /** Adopts the exact token values from the pre-multi-tenant single-DO
   *  deployment (workspace_id "default") — never generates new ones, so
   *  the already-registered ChatGPT connector's tokens keep working once
   *  its Server URL gains the /default/ segment. */
  migrateDefault({ gptToken, linkToken, cliToken } = {}) {
    if (this.hasSecrets()) return { error: "ALREADY_PROVISIONED" };
    if (typeof gptToken !== "string" || typeof linkToken !== "string" || typeof cliToken !== "string") {
      return { error: "INVALID_ARGS" };
    }
    this.setSecret("gpt_token", gptToken);
    this.setSecret("link_token", linkToken);
    this.setSecret("cli_token", cliToken);
    return { ok: true };
  }

  // ---- rate limiting (sliding window, best-effort across hibernation) ----

  rateLimit(key, maxPerMinute) {
    const now = Date.now();
    const windowStart = now - 60_000;
    const arr = (this.rateBuckets.get(key) || []).filter((t) => t > windowStart);
    if (arr.length >= maxPerMinute) {
      this.rateBuckets.set(key, arr);
      return false;
    }
    arr.push(now);
    this.rateBuckets.set(key, arr);
    return true;
  }

  // ======================= /link : local bridge WebSocket =======================

  async handleLink(request, token) {
    if (!this.checkToken("link_token", token)) return new Response("not found", { status: 404 });
    if (request.headers.get("upgrade") !== "websocket") {
      return new Response("expected websocket", { status: 426 });
    }
    if (!this.rateLimit("link", 10)) {
      return new Response("rate limited", { status: 429, headers: { "retry-after": "60" } });
    }

    // Single-connection constraint: the newest connection wins. Closing the old
    // one lets a local bridge restart (crash, reboot, network blip) reconnect
    // without any manual cleanup.
    for (const ws of this.ctx.getWebSockets("local")) {
      try {
        ws.close(1008, "superseded by new connection");
      } catch {
        /* already closing */
      }
    }

    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair);
    this.ctx.acceptWebSocket(server, ["local"]);
    server.serializeAttachment({ connected_at: Date.now() });

    return new Response(null, { status: 101, webSocket: client });
  }

  webSocketMessage(_ws, message) {
    let msg;
    try {
      msg = JSON.parse(typeof message === "string" ? message : new TextDecoder().decode(message));
    } catch {
      return;
    }
    const pending = this.pending.get(msg.rid);
    if (!pending) return; // stale or unsolicited; ignore
    clearTimeout(pending.timer);
    this.pending.delete(msg.rid);
    pending.resolve(msg);
  }

  webSocketClose() {
    this.failAllPending();
  }

  webSocketError() {
    this.failAllPending();
  }

  failAllPending() {
    for (const [, p] of this.pending) {
      clearTimeout(p.timer);
      p.resolve({ ok: false, error: { status: "local_disconnected" } });
    }
    this.pending.clear();
  }

  /** Send a request to the local bridge over the WS link and await its reply.
   *  Uses our own `rid`, never the MCP request `id` (which ChatGPT may reuse
   *  across concurrent tool calls). */
  async callLocal(method, params) {
    const sockets = this.ctx.getWebSockets("local");
    if (sockets.length === 0) return { ok: false, error: { status: "local_offline" } };
    const rid = crypto.randomUUID();
    const ws = sockets[0];
    return new Promise((resolve) => {
      const timer = setTimeout(() => {
        this.pending.delete(rid);
        resolve({ ok: false, error: { status: "timeout" } });
      }, RPC_TIMEOUT_MS);
      this.pending.set(rid, { resolve, timer });
      try {
        ws.send(JSON.stringify({ rid, method, params }));
      } catch {
        clearTimeout(timer);
        this.pending.delete(rid);
        resolve({ ok: false, error: { status: "local_offline" } });
      }
    });
  }

  // ======================= /mcp : ChatGPT-facing JSON-RPC =======================

  async handleMcpRoute(request, token) {
    if (!this.checkToken("gpt_token", token)) return new Response("not found", { status: 404 });
    if (request.method === "GET" || request.method === "DELETE") {
      return new Response(null, { status: 405, headers: { allow: "POST" } });
    }
    if (request.method !== "POST") {
      return new Response(null, { status: 405, headers: { allow: "POST" } });
    }
    if (!this.rateLimit("mcp", 60)) {
      return new Response("rate limited", { status: 429, headers: { "retry-after": "60" } });
    }
    const contentType = request.headers.get("content-type") || "";
    if (!contentType.includes("application/json")) {
      return new Response("unsupported media type", { status: 415 });
    }
    const protocolVersion = checkProtocolVersion(request);
    if (protocolVersion === null) {
      return new Response("unsupported MCP-Protocol-Version", { status: 400 });
    }

    const parsed = await readJsonWithLimit(request, MAX_REQUEST_BYTES);
    if (parsed.tooLarge) return new Response("payload too large", { status: 413 });
    if (parsed.parseError) return rpcError(null, -32700, "Parse error");
    const payload = parsed.value;

    if (Array.isArray(payload)) {
      // JSON-RPC batching was removed in MCP 2025-06-18.
      return new Response("JSON-RPC batching is not supported", { status: 400 });
    }
    if (!payload || typeof payload !== "object" || payload.jsonrpc !== "2.0") {
      return rpcError(payload && payload.id, -32600, "Invalid Request");
    }

    if (!("method" in payload)) {
      // A bare JSON-RPC *response* sent to us: accept and discard.
      return new Response(null, { status: 202 });
    }
    if (!("id" in payload)) {
      // A JSON-RPC *notification* (e.g. notifications/initialized): accept, no reply expected.
      return new Response(null, { status: 202 });
    }

    return this.handleMcpRequest(payload);
  }

  // ======================= shared /mcp : one ChatGPT connector =======================

  async handleHubMcpRoute(request, token) {
    if (!this.checkToken("hub_gpt_token", token)) return new Response("not found", { status: 404 });
    if (request.method === "GET" || request.method === "DELETE") {
      return new Response(null, { status: 405, headers: { allow: "POST" } });
    }
    if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });
    if (!this.rateLimit("hub-mcp", 60)) return new Response("rate limited", { status: 429, headers: { "retry-after": "60" } });
    if (!(request.headers.get("content-type") || "").includes("application/json")) {
      return new Response("unsupported media type", { status: 415 });
    }
    if (checkProtocolVersion(request) === null) return new Response("unsupported MCP-Protocol-Version", { status: 400 });

    const parsed = await readJsonWithLimit(request, MAX_REQUEST_BYTES);
    if (parsed.tooLarge) return new Response("payload too large", { status: 413 });
    if (parsed.parseError) return rpcError(null, -32700, "Parse error");
    const payload = parsed.value;
    if (Array.isArray(payload)) return new Response("JSON-RPC batching is not supported", { status: 400 });
    if (!payload || typeof payload !== "object" || payload.jsonrpc !== "2.0") return rpcError(payload && payload.id, -32600, "Invalid Request");
    if (!("method" in payload) || !("id" in payload)) return new Response(null, { status: 202 });
    return this.handleHubMcpRequest(payload);
  }

  async handleHubMcpRequest({ id, method, params }) {
    switch (method) {
      case "ping":
        return json({ jsonrpc: "2.0", id, result: {} });
      case "initialize": {
        const clientVersion = params && params.protocolVersion;
        const version = PROTOCOL_VERSIONS.has(clientVersion) ? clientVersion : "2025-06-18";
        return json({ jsonrpc: "2.0", id, result: { protocolVersion: version, capabilities: { tools: {} }, serverInfo: { name: "gpt-worker", version: "1.1.0" } } });
      }
      case "tools/list":
        return json({ jsonrpc: "2.0", id, result: { tools: HUB_TOOLS.map(({ name, title, description, inputSchema, annotations }) => ({ name, title, description, inputSchema, annotations })) } });
      case "tools/call":
        return this.handleHubToolCall(id, params);
      default:
        return rpcError(id, -32601, `Method not found: ${method}`);
    }
  }

  registeredWorkspaces() {
    return this.sql.exec(`SELECT workspace_id, name, registered_at FROM workspace_registry ORDER BY name COLLATE NOCASE`).toArray();
  }

  async handleHubToolCall(id, params) {
    if (!params || typeof params.name !== "string") return rpcError(id, -32602, "Invalid params: missing tool name");
    const { name, arguments: args = {} } = params;
    if (name === "list_workspaces") return json({ jsonrpc: "2.0", id, result: toolOk({ workspaces: this.registeredWorkspaces() }) });
    if (!HUB_TOOLS.some((tool) => tool.name === name)) {
      return json({ jsonrpc: "2.0", id, result: toolError("UNKNOWN_TOOL", `No such tool: ${name}`) });
    }
    const workspaceId = args && args.workspace_id;
    if (!isValidWorkspaceId(workspaceId) || !this.registeredWorkspaces().some((w) => w.workspace_id === workspaceId)) {
      return json({ jsonrpc: "2.0", id, result: toolError("UNKNOWN_WORKSPACE", "Call list_workspaces and pass one returned workspace_id.") });
    }
    const forwardedArgs = { ...args };
    delete forwardedArgs.workspace_id;
    try {
      const stub = this.env.BRIDGE_DO.get(this.env.BRIDGE_DO.idFromName(workspaceId));
      const response = await stub.fetch(new Request("https://gpt-worker.internal/hub", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ name, arguments: forwardedArgs }),
      }));
      const result = await response.json();
      return json({ jsonrpc: "2.0", id, result });
    } catch (err) {
      return json({ jsonrpc: "2.0", id, result: toolError("WORKSPACE_UNAVAILABLE", String((err && err.message) || err)) });
    }
  }

  /** Internal, binding-only entry point used by the hub to preserve the
   * existing workspace task queues and read gating. */
  async handleHubRelay(request) {
    if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });
    const parsed = await readJsonWithLimit(request, MAX_REQUEST_BYTES);
    if (parsed.tooLarge) return json(toolError("PAYLOAD_TOO_LARGE", "request exceeds size limit"), 413);
    const body = parsed.value || {};
    if (parsed.parseError || typeof body.name !== "string") return json(toolError("INVALID_ARGS", "tool name is required"), 400);
    return json(await this.invokeTool(body.name, body.arguments || {}));
  }

  async handleMcpRequest({ id, method, params }) {
    switch (method) {
      case "ping":
        return json({ jsonrpc: "2.0", id, result: {} });

      case "initialize": {
        const clientVersion = params && params.protocolVersion;
        const version = PROTOCOL_VERSIONS.has(clientVersion) ? clientVersion : "2025-06-18";
        return json({
          jsonrpc: "2.0",
          id,
          result: {
            protocolVersion: version,
            capabilities: { tools: {} },
            serverInfo: { name: "gpt-worker", version: "1.0.0" },
          },
        });
      }

      case "tools/list": {
        const tools = TOOLS.tools.map((t) => ({
          name: t.name,
          title: t.title,
          description: t.description,
          inputSchema: t.inputSchema,
          annotations: t.annotations,
        }));
        return json({ jsonrpc: "2.0", id, result: { tools } });
      }

      case "tools/call":
        return this.handleToolCall(id, params);

      default:
        return rpcError(id, -32601, `Method not found: ${method}`);
    }
  }

  async handleToolCall(id, params) {
    if (!params || typeof params.name !== "string") {
      return rpcError(id, -32602, "Invalid params: missing tool name");
    }
    const { name, arguments: args = {} } = params;
    return json({ jsonrpc: "2.0", id, result: await this.invokeTool(name, args) });
  }

  async invokeTool(name, args = {}) {
    const tool = TOOLS.tools.find((t) => t.name === name);
    if (!tool) return toolError("UNKNOWN_TOOL", `No such tool: ${name}`);
    try {
      if (tool.location === "queue_next") return toolOk(this.queueNext(args && args.task_id));
      if (tool.location === "queue_submit") return this.queueSubmit(args);
      if (tool.location === "queue_history") return toolOk(this.taskHistory(args));
      if (tool.location === "workspace_guidance") return toolOk(this.workspaceGuidance());
      const relay = await this.callLocal(name, {
        ...args,
        // The bridge treats this as Worker-authenticated control metadata,
        // never as a value supplied by ChatGPT. It keeps workspace reads
        // gated by the Worker-owned task state without persisting a local
        // copy of the active task ID.
        __gptWorkerActiveTask: this.isActiveTaskWindow(),
      });
      if (!relay.ok) return toolOk(relay.error);
      return toolOk(relay.result);
    } catch (err) {
      return toolError("INTERNAL_ERROR", String((err && err.message) || err));
    }
  }

  // ---- postbox: to_gpt / to_local queues, backed by SQLite ----

  /** taskId is optional: when given (e.g. the user's message named a
   *  specific task), only that task's oldest undelivered message is
   *  eligible — no fallback to a different task if it isn't there, since
   *  silently substituting one would be more confusing than {empty:true}. */
  queueNext(taskId) {
    const now = Date.now();
    const rows = (
      typeof taskId === "string" && taskId
        ? this.sql.exec(
            `SELECT * FROM msgs
             WHERE dir = 'to_gpt' AND task_id = ? AND (state = 'pending' OR (state = 'leased' AND lease_until < ?))
             ORDER BY created_at ASC LIMIT 1`,
            taskId,
            now
          )
        : this.sql.exec(
            `SELECT * FROM msgs
             WHERE dir = 'to_gpt' AND (state = 'pending' OR (state = 'leased' AND lease_until < ?))
             ORDER BY created_at ASC LIMIT 1`,
            now
          )
    ).toArray();
    if (rows.length === 0) return { empty: true };
    const row = rows[0];
    this.sql.exec(`UPDATE msgs SET state = 'leased', lease_until = ? WHERE message_id = ?`, now + LEASE_MS, row.message_id);
    return {
      empty: false,
      message_id: row.message_id,
      task_id: row.task_id,
      iteration: row.iteration,
      kind: row.kind,
      body: row.body,
    };
  }

  queueSubmit(args) {
    const { task_id, iteration, state, body } = args || {};
    if (
      typeof task_id !== "string" ||
      typeof iteration !== "number" ||
      !["PLAN", "DONE", "BLOCKED"].includes(state) ||
      typeof body !== "string"
    ) {
      return toolError("INVALID_ARGS", "task_id, iteration, state and body are required");
    }
    if (byteLength(body) > MAX_BODY_BYTES) {
      return toolError("BODY_TOO_LARGE", `body exceeds ${MAX_BODY_BYTES} bytes`);
    }

    const matches = this.sql
      .exec(
        `SELECT message_id FROM msgs WHERE dir = 'to_gpt' AND task_id = ? AND iteration = ? AND state != 'acked'`,
        task_id,
        iteration
      )
      .toArray();
    if (matches.length === 0) {
      return toolError("NO_MATCHING_TASK", `No open INIT/EXECUTED for task_id=${task_id} iteration=${iteration}`);
    }
    const task = this.getTask(task_id);
    if (
      !task ||
      ["DONE", "BLOCKED"].includes(task.protocol_state) ||
      !["WAITING_PLAN", "WAITING_REVIEW"].includes(task.protocol_state) ||
      task.iteration !== iteration
    ) {
      return toolError("NO_MATCHING_TASK", `No active task for task_id=${task_id} iteration=${iteration}`);
    }
    for (const m of matches) {
      this.sql.exec(`UPDATE msgs SET state = 'acked' WHERE message_id = ?`, m.message_id);
    }

    const now = Date.now();
    if (state === "PLAN") {
      this.sql.exec(
        `UPDATE tasks SET protocol_state = 'EXECUTING', waiting_for = 'none', updated_at = ? WHERE task_id = ?`,
        now,
        task_id
      );
    } else {
      this.sql.exec(
        `UPDATE tasks
         SET protocol_state = ?, waiting_for = ?, terminal_summary = ?, updated_at = ?
         WHERE task_id = ?`,
        state,
        state === "BLOCKED" ? "USER" : "none",
        body,
        now,
        task_id
      );
    }

    const messageId = crypto.randomUUID();
    this.sql.exec(
      `INSERT INTO msgs (message_id, dir, task_id, iteration, kind, body, state, lease_until, created_at)
       VALUES (?, 'to_local', ?, ?, ?, ?, 'pending', NULL, ?)`,
      messageId,
      task_id,
      iteration,
      state,
      body,
      now
    );
    // Best-effort immediate push; the CLI's /local poll (below) is the
    // authoritative delivery path and does not depend on this succeeding.
    this.callLocal("plan_pushed", { message_id: messageId }).catch(() => {});
    return toolOk({ message_id: messageId });
  }

  /** Past tasks that reached a terminal state (DONE/BLOCKED), newest first —
   *  lets GPT orient itself in a fresh conversation without depending
   *  solely on this Project's own (less reliable) memory. Lives entirely
   *  in this queue's SQLite, so unlike the 7 workspace tools it works even
   *  while the local bridge is offline. This checks `kind`, not `state`:
   *  DONE/BLOCKED is a conclusion GPT itself already reached, regardless of
   *  whether the local CLI has polled and acked it yet (a message can sit
   *  'pending' for a while if the bridge was offline) — only an in-flight
   *  PLAN (a different kind) isn't "history" yet. */
  taskHistory(args) {
    const limit = Math.min(Math.max(Number(args && args.limit) || 20, 1), 100);
    const rows = this.sql
      .exec(
        `SELECT task_id, protocol_state, terminal_summary, updated_at FROM tasks
         WHERE protocol_state IN ('DONE', 'BLOCKED')
         ORDER BY updated_at DESC LIMIT ?`,
        limit
      )
      .toArray();
    return {
      tasks: rows.map((r) => ({
        task_id: r.task_id,
        outcome: r.protocol_state,
        summary: (r.terminal_summary || "").length > 500 ? r.terminal_summary.slice(0, 500) + "…" : r.terminal_summary || "",
        created_at: r.updated_at,
      })),
    };
  }

  getTask(taskId) {
    const rows = this.sql.exec(`SELECT * FROM tasks WHERE task_id = ?`, taskId).toArray();
    return rows.length ? rows[0] : null;
  }

  activeTask() {
    const rows = this.sql
      .exec(`SELECT * FROM tasks WHERE protocol_state NOT IN ('DONE', 'BLOCKED') ORDER BY updated_at DESC LIMIT 1`)
      .toArray();
    return rows.length ? rows[0] : null;
  }

  taskView(task) {
    if (!task) return null;
    return {
      taskId: task.task_id,
      goal: task.goal,
      iteration: task.iteration,
      protocolState: task.protocol_state,
      waitingFor: task.waiting_for,
      taskStartedAt: task.task_started_at,
      updatedAt: task.updated_at,
      terminalSummary: task.terminal_summary || null,
    };
  }

  isActiveTaskWindow() {
    const task = this.activeTask();
    return !!task && Date.now() - task.task_started_at < ACTIVE_WINDOW_MS;
  }

  workspaceGuidance() {
    const rows = this.sql.exec(`SELECT v FROM settings WHERE k = 'guidance'`).toArray();
    const guidance = rows.length ? rows[0].v : "";
    return guidance ? { set: true, guidance } : { set: false };
  }

  // ======================= /local : CLI-facing HTTP =======================

  async handleLocalRoute(request, token) {
    if (!this.checkToken("cli_token", token)) return new Response("not found", { status: 404 });
    if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });
    if (!this.rateLimit("local", 120)) {
      return new Response("rate limited", { status: 429, headers: { "retry-after": "60" } });
    }
    const parsed = await readJsonWithLimit(request, MAX_REQUEST_BYTES);
    if (parsed.tooLarge) return new Response("payload too large", { status: 413 });
    if (parsed.parseError) return json({ error: "PARSE_ERROR" }, 400);
    const body = parsed.value;
    switch (body && body.op) {
      case "enqueue":
        return json(this.localEnqueue(body));
      case "start_task":
        return json(this.localStartTask(body));
      case "report_task":
        return json(this.localReportTask(body));
      case "active_task":
        return json({ task: this.taskView(this.activeTask()) });
      case "migrate_legacy_state":
        return json(this.localMigrateLegacyState(body));
      case "settings_get":
        return json(this.localSettingsGet());
      case "settings_set":
        return json(this.localSettingsSet(body));
      case "guidance_set":
        return json(this.localGuidanceSet(body));
      case "guidance_get":
        return json(this.workspaceGuidance());
      case "guidance_clear":
        return json(this.localGuidanceClear());
      case "poll":
        return json(await this.localPoll(body));
      case "ack":
        return json(this.localAck(body));
      case "status":
        return json(this.localStatus());
      case "list":
        return json(this.localList(body));
      case "discard_task":
        return json(this.localDiscardTask(body));
      case "discard":
        return json(this.localDiscard(body));
      default:
        return json({ error: "UNKNOWN_OP" }, 400);
    }
  }

  /** Ad-hoc cleanup of one message by id, either direction — for manually
   *  clearing test/abandoned entries found via `gpt-worker queue`. */
  localDiscard(body) {
    if (typeof body.message_id !== "string") return { error: "INVALID_ARGS" };
    this.sql.exec(`UPDATE msgs SET state = 'acked' WHERE message_id = ?`, body.message_id);
    return { ok: true };
  }

  /** Marks every not-yet-acked to_gpt message for a task_id as acked, without
   *  requiring a matching submit_plan. Used when `gpt-worker task --force`
   *  replaces an unfinished task — otherwise the abandoned INIT/EXECUTED
   *  would sit in the queue forever and next_task() could hand it to
   *  ChatGPT ahead of the new task's message. */
  localDiscardTask(body) {
    if (typeof body.task_id !== "string") return { error: "INVALID_ARGS" };
    this.sql.exec(`UPDATE msgs SET state = 'acked' WHERE dir = 'to_gpt' AND task_id = ? AND state != 'acked'`, body.task_id);
    this.sql.exec(
      `UPDATE tasks
       SET protocol_state = 'BLOCKED', waiting_for = 'none', terminal_summary = 'Task replaced or discarded locally.', updated_at = ?
       WHERE task_id = ? AND protocol_state NOT IN ('DONE', 'BLOCKED')`,
      Date.now(),
      body.task_id
    );
    return { ok: true };
  }

  localStartTask(body) {
    const { task_id: taskId, goal, text, force } = body || {};
    if (typeof taskId !== "string" || typeof goal !== "string" || typeof text !== "string") {
      return { error: "INVALID_ARGS" };
    }
    const active = this.activeTask();
    if (active && !force) return { error: "ACTIVE_TASK", task: this.taskView(active) };
    if (active) this.localDiscardTask({ task_id: active.task_id });

    const now = Date.now();
    this.sql.exec(
      `INSERT INTO tasks (task_id, goal, iteration, protocol_state, waiting_for, task_started_at, updated_at)
       VALUES (?, ?, 0, 'WAITING_PLAN', 'GPT_PLAN', ?, ?)`,
      taskId,
      goal,
      now,
      now
    );
    const queued = this.localEnqueue({ kind: "INIT", task_id: taskId, iteration: 0, body: text });
    if (queued.error) return queued;
    return { task: this.taskView(this.getTask(taskId)), ...queued };
  }

  localReportTask(body) {
    const { task_id: taskId, changed, tests, text } = body || {};
    if (typeof taskId !== "string" || typeof text !== "string") return { error: "INVALID_ARGS" };
    const task = this.getTask(taskId);
    if (!task) return { error: "NO_ACTIVE_TASK" };
    const nextIteration = task.iteration + 1;
    if (task.protocol_state !== "EXECUTING") return { error: "INVALID_STATE", state: task.protocol_state };
    const queued = this.localEnqueue({ kind: "EXECUTED", task_id: taskId, iteration: nextIteration, body: text });
    if (queued.error) return queued;
    this.sql.exec(
      `UPDATE tasks SET iteration = ?, protocol_state = 'WAITING_REVIEW', waiting_for = 'GPT_REVIEW', updated_at = ? WHERE task_id = ?`,
      nextIteration,
      Date.now(),
      taskId
    );
    return { task: this.taskView(this.getTask(taskId)), changed, tests, ...queued };
  }

  localMigrateLegacyState(body) {
    const { taskId, goal, iteration, protocolState, waitingFor, taskStartedAt } = body || {};
    if (this.activeTask()) return { task: this.taskView(this.activeTask()), migrated: false };
    if (
      typeof taskId !== "string" || typeof goal !== "string" || !Number.isInteger(iteration) ||
      !["WAITING_PLAN", "EXECUTING", "WAITING_REVIEW"].includes(protocolState)
    ) return { error: "INVALID_ARGS" };
    const now = Date.now();
    this.sql.exec(
      `INSERT OR IGNORE INTO tasks (task_id, goal, iteration, protocol_state, waiting_for, task_started_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      taskId, goal, iteration, protocolState, typeof waitingFor === "string" ? waitingFor : "none",
      Number.isFinite(taskStartedAt) ? taskStartedAt : now, now
    );
    return { task: this.taskView(this.getTask(taskId)), migrated: true };
  }

  localSettingsGet() {
    const rows = this.sql.exec(`SELECT k, v FROM settings WHERE k IN ('chat_url', 'auto_enter', 'enter_delay_ms')`).toArray();
    const values = Object.fromEntries(rows.map((r) => [r.k, r.v]));
    return {
      chatUrl: values.chat_url || null,
      autoEnter: values.auto_enter === "true",
      enterDelayMs: values.enter_delay_ms ? Number(values.enter_delay_ms) : null,
    };
  }

  localSettingsSet(body) {
    const { chatUrl, autoEnter, enterDelayMs } = body || {};
    if (chatUrl !== undefined) this.setSetting("chat_url", chatUrl || "");
    if (autoEnter !== undefined) this.setSetting("auto_enter", autoEnter ? "true" : "false");
    if (enterDelayMs !== undefined) this.setSetting("enter_delay_ms", enterDelayMs === null ? "" : String(enterDelayMs));
    return this.localSettingsGet();
  }

  localGuidanceSet(body) {
    if (!body || typeof body.text !== "string") return { error: "INVALID_ARGS" };
    if (byteLength(body.text) > 8 * 1024) return { error: "BODY_TOO_LARGE" };
    this.setSetting("guidance", body.text);
    return { ok: true };
  }

  localGuidanceClear() {
    this.setSetting("guidance", "");
    return { ok: true };
  }

  setSetting(key, value) {
    this.sql.exec(`INSERT OR REPLACE INTO settings (k, v) VALUES (?, ?)`, key, value);
  }

  /** Debug/inspection: every not-yet-acked message in both directions, oldest
   *  first, with the body truncated for display. Not used by the normal
   *  task/wait/report loop — this is what `gpt-worker queue` calls. */
  localList(body) {
    const taskId = body && typeof body.task_id === "string" ? body.task_id : null;
    const rows = (
      taskId
        ? this.sql.exec(`SELECT * FROM msgs WHERE state != 'acked' AND task_id = ? ORDER BY created_at ASC LIMIT 100`, taskId)
        : this.sql.exec(`SELECT * FROM msgs WHERE state != 'acked' ORDER BY created_at ASC LIMIT 100`)
    ).toArray();
    const now = Date.now();
    return {
      messages: rows.map((r) => ({
        message_id: r.message_id,
        dir: r.dir,
        task_id: r.task_id,
        iteration: r.iteration,
        kind: r.kind,
        // The DB row can say 'leased' after its lease_until has already
        // passed — queueNext() already treats that as available again, so
        // report it that way here too rather than showing a stale "leased".
        state: r.state === "leased" && r.lease_until && r.lease_until < now ? "pending" : r.state,
        created_at: r.created_at,
        body_preview: r.body.length > 200 ? r.body.slice(0, 200) + "…" : r.body,
      })),
    };
  }

  localEnqueue(body) {
    const { kind, task_id, iteration, body: text } = body;
    if (
      !["INIT", "EXECUTED"].includes(kind) ||
      typeof task_id !== "string" ||
      typeof iteration !== "number" ||
      !Number.isInteger(iteration) ||
      typeof text !== "string"
    ) {
      return { error: "INVALID_ARGS" };
    }
    // Protocol invariant (reference/protocol.md): INIT always starts a task
    // at iteration 0; every EXECUTED reports on a round that already had an
    // INIT, so it is always >= 1.
    if (kind === "INIT" && iteration !== 0) {
      return { error: "INVALID_ITERATION", message: "INIT must be iteration 0" };
    }
    if (kind === "EXECUTED" && iteration < 1) {
      return { error: "INVALID_ITERATION", message: "EXECUTED must be iteration >= 1" };
    }
    if (byteLength(text) > MAX_BODY_BYTES) return { error: "BODY_TOO_LARGE" };

    // Kept for the narrow legacy/debug enqueue endpoint. The normal CLI path
    // uses localStartTask(), but direct INIT callers still receive a durable
    // task row instead of silently creating queue-only state.
    if (kind === "INIT" && !this.getTask(task_id)) {
      const now = Date.now();
      this.sql.exec(
        `INSERT INTO tasks (task_id, goal, iteration, protocol_state, waiting_for, task_started_at, updated_at)
         VALUES (?, '', 0, 'WAITING_PLAN', 'GPT_PLAN', ?, ?)`,
        task_id,
        now,
        now
      );
    }

    // Idempotent retry: a CLI retry after a dropped response (the write
    // landed but the HTTP reply didn't) must not create a second physical
    // row for the same round — reuse the existing message_id instead. This
    // check-then-insert is safe without extra locking because a Durable
    // Object runs at most one request's synchronous SQL calls at a time.
    const existing = this.sql
      .exec(`SELECT message_id FROM msgs WHERE dir = 'to_gpt' AND task_id = ? AND iteration = ?`, task_id, iteration)
      .toArray();
    if (existing.length > 0) return { message_id: existing[0].message_id, idempotent: true };

    const messageId = crypto.randomUUID();
    const now = Date.now();
    this.sql.exec(
      `INSERT INTO msgs (message_id, dir, task_id, iteration, kind, body, state, lease_until, created_at)
       VALUES (?, 'to_gpt', ?, ?, ?, ?, 'pending', NULL, ?)`,
      messageId,
      task_id,
      iteration,
      kind,
      text,
      now
    );
    return { message_id: messageId };
  }

  async localPoll(body) {
    const timeoutMs = Math.min(Math.max(Number(body.timeout_ms) || 0, 0), POLL_MAX_MS);
    const deadline = Date.now() + timeoutMs;
    for (;;) {
      const rows = this.sql
        .exec(`SELECT * FROM msgs WHERE dir = 'to_local' AND state != 'acked' ORDER BY created_at ASC LIMIT 20`)
        .toArray();
      if (rows.length > 0) {
        return {
          messages: rows.map((r) => ({
            message_id: r.message_id,
            task_id: r.task_id,
            iteration: r.iteration,
            kind: r.kind,
            body: r.body,
          })),
        };
      }
      if (Date.now() >= deadline) return { messages: [] };
      await sleep(1000);
    }
  }

  localAck(body) {
    if (typeof body.message_id !== "string") return { error: "INVALID_ARGS" };
    this.sql.exec(`UPDATE msgs SET state = 'acked' WHERE message_id = ? AND dir = 'to_local'`, body.message_id);
    return { ok: true };
  }

  localStatus() {
    const connected = this.ctx.getWebSockets("local").length > 0;
    const pendingToGpt = this.sql.exec(`SELECT COUNT(*) AS n FROM msgs WHERE dir='to_gpt' AND state != 'acked'`).toArray()[0].n;
    const pendingToLocal = this.sql.exec(`SELECT COUNT(*) AS n FROM msgs WHERE dir='to_local' AND state != 'acked'`).toArray()[0].n;
    return { connected, pendingToGpt, pendingToLocal };
  }

  // ======================= maintenance =======================

  async alarm() {
    const cutoff = Date.now() - RETENTION_MS;
    this.sql.exec(`DELETE FROM msgs WHERE state = 'acked' AND created_at < ?`, cutoff);
    await this.ctx.storage.setAlarm(Date.now() + ALARM_INTERVAL_MS);
  }
}
