// gpt-worker relay.
//
// One Worker, many workspaces: each workspace gets its own Durable Object
// instance (keyed by workspace_id), so each has an independent queue, its
// own 3 tokens, and its own /link WebSocket — starting the bridge for one
// workspace never evicts another's connection.
//
//   /mcp, /mcp/<workspace_id>          OAuth-protected ChatGPT-facing MCP resources.
//                                       The shared resource exposes registered workspaces as an
//                                       explicit tool argument.
//   /local/<workspace_id>/<cli_token> CLI-facing postbox API (enqueue / poll / ack / status).
//   /link/<workspace_id>/<link_token> WebSocket reverse-connection from the local bridge process.
//   /admin/<ADMIN_TOKEN>              Provision a new workspace_id, or migrate an old
//                                     single-tenant deployment's tokens into one. Never
//                                     appears in a per-workspace URL; set once machine-wide.
//
//   /.well-known/oauth-protected-resource[/mcp[/<workspace_id>]]
//   /.well-known/oauth-authorization-server
//                                       RFC 9728 / OAuth AS discovery metadata for the above.
//
// workspace_id is a routing key, not a secret — it just selects which Durable
// Object instance handles the request. The actual gpt/link/cli tokens are
// generated by /admin and stored *inside* that instance's own SQLite (a
// `secrets` table), which is why token validation now happens inside the
// Durable Object rather than here at the top level: only that instance knows
// its own tokens.
//
// The Durable Object (BridgeDO) is the only stateful piece: it holds the message
// queue (SQLite) and the live WebSocket link to the local bridge, using the
// WebSocket Hibernation API so it costs nothing while idle.
//
// See ~/.agents/skills/gpt-worker/SKILL.md for the operating protocol and
// ~/.agents/skills/gpt-worker/reference/protocol.md for message formats.

// Stateless helpers extracted from this file (see each module's own header
// comment for its scope and dependency rules) — index.js depends on them,
// never the reverse.
import { isValidWorkspaceId, constantTimeEqual, checkOrigin, json, readJsonWithLimit } from "./worker-http.js";
import {
  oauthResourceUrl,
  oauthProtectedResourceMetadataUrl,
  oauthProtectedResourceMetadata,
  oauthAuthorizationServerMetadata,
  oauthError,
  parseOAuthForm,
} from "./worker-oauth-http.js";
import { initializeBridgeSchema } from "./bridge-schema.js";
import { createBridgeProtocol } from "./bridge-protocol.js";
import { createBridgeAdmin, MAX_BODY_BYTES_CEILING, REQUEST_ENVELOPE_OVERHEAD_BYTES } from "./bridge-admin.js";
import { createBridgeOAuth } from "./bridge-oauth.js";
import { createBridgeMcp, toolOk, toolError } from "./bridge-mcp.js";
import { createBridgeTransport } from "./bridge-transport.js";
import { createBridgeDashboard } from "./bridge-dashboard.js";

const MAX_REQUEST_BYTES = 32 * 1024; // the whole JSON-RPC/CLI envelope around it
// Used only where the target workspace isn't known yet (the shared
// connector's hub-level envelope parse, before it has read which workspace
// the call is for) — see handleOAuthMcpDispatch. The real, per-workspace
// limit is enforced once the call reaches that workspace's own DO.
// MAX_BODY_BYTES_CEILING/REQUEST_ENVELOPE_OVERHEAD_BYTES themselves are
// owned by bridge-admin.js (the per-workspace `body` size cap is admin/
// settings domain state) and imported above; this cross-target constant
// stays defined here since it isn't specific to that domain.
const MAX_REQUEST_BYTES_CEILING = MAX_BODY_BYTES_CEILING + REQUEST_ENVELOPE_OVERHEAD_BYTES;
const RETENTION_MS = 7 * 24 * 60 * 60 * 1000;
// Longer than RETENTION_MS on purpose: `tasks` rows back the queue_history
// tool's cross-conversation memory for ChatGPT, which is only useful if it
// outlives a single week-long gap between sessions. msgs rows are pure
// message-delivery transport and don't need that longevity.
const TASK_RETENTION_MS = 30 * 24 * 60 * 60 * 1000;
const ALARM_INTERVAL_MS = 24 * 60 * 60 * 1000;
// OAuth TTLs, PKCE/state/scope/redirect-uri constants and validation are
// owned by bridge-oauth.js now (Phase 2C) — see that module for
// OAUTH_CODE_TTL_MS/OAUTH_ACCESS_TTL_MS/OAUTH_REFRESH_TTL_MS/
// PKCE_CHALLENGE_RE/PKCE_VERIFIER_RE and friends.
const HUB_DO_NAME = "gpt-worker-hub";

// ---------------------------------------------------------------------------
// Top-level Worker: validate path shape, then hand off to the right
// per-workspace Durable Object. Per-workspace token validation happens
// *inside* the Durable Object (see BridgeDO.checkToken) — this layer only
// ever sees workspace_id (not secret) and, for /admin, ADMIN_TOKEN.
// ---------------------------------------------------------------------------

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const parts = url.pathname.split("/").filter(Boolean);

    // OAuth discovery metadata is public (no Origin/token gating) and lives
    // outside every other route shape below.
    if (parts[0] === ".well-known") {
      return handleOAuthMetadataRoute(request, parts);
    }

    // OAuth authorization server endpoints advertised by the metadata above.
    if (parts.length === 2 && parts[0] === "oauth" && parts[1] === "authorize") {
      return handleOAuthAuthorizeRoute(request, env);
    }
    if (parts.length === 2 && parts[0] === "oauth" && parts[1] === "token") {
      return handleOAuthTokenRoute(request, env);
    }
    if (parts.length === 2 && parts[0] === "oauth" && parts[1] === "register") {
      return handleOAuthRegisterRoute(request, env);
    }

    // Secret-free OAuth resource URL, shared connector: exactly "/mcp".
    if (parts.length === 1 && parts[0] === "mcp") {
      return handleOAuthMcpResource(request, env, undefined);
    }

    if (parts.length === 2 && parts[0] === "admin") {
      return handleAdminRoute(request, env, parts[1]);
    }

    // OAuth resource URL, per-workspace: "/mcp/<workspace_id>".
    if (parts.length === 2 && parts[0] === "mcp" && isValidWorkspaceId(parts[1])) {
      return handleOAuthMcpResource(request, env, parts[1]);
    }

    // Workspace-owner Web dashboard: "/dashboard/<workspace_id>[/...]"
    // (docs/plans/queue-dashboard.md). This top-level layer only validates
    // workspace_id's shape and forwards — session/login verification happens
    // entirely inside the target DO (see BridgeDO.handleDashboard), same
    // division of responsibility as every other route here.
    if (parts[0] === "dashboard") {
      // Shared hub dashboard: "/dashboard/hub[/...]" — every registered
      // workspace, one owner login (the shared hub_gpt_token). "hub" can
      // never collide with a real workspace_id (isValidWorkspaceId requires
      // 16 hex chars or the legacy "default"), so this check ahead of the
      // per-workspace one below never shadows a real workspace's route.
      // Login/session/CSRF/rate-limit verification happens entirely inside
      // the hub DO (see BridgeDO.handleHubDashboard), same division of
      // responsibility as the per-workspace dashboard.
      if (parts.length >= 2 && parts[1] === "hub") {
        const hub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(HUB_DO_NAME));
        const forwardUrl = new URL(request.url);
        forwardUrl.pathname = `/dashboard/hub${parts.length > 2 ? "/" + parts.slice(2).join("/") : ""}`;
        return hub.fetch(new Request(forwardUrl, request));
      }
      if (parts.length < 2 || !isValidWorkspaceId(parts[1])) return new Response("not found", { status: 404 });
      const workspaceId = parts[1];
      const doId = env.BRIDGE_DO.idFromName(workspaceId);
      const stub = env.BRIDGE_DO.get(doId);
      const forwardUrl = new URL(request.url);
      // workspace_id travels *into* the internal path (unlike /link,/local,
      // which drop it once it has selected the DO instance) because the DO
      // needs it verbatim to scope the session cookie's Path — see
      // dashboardSessionCookie(). It carries no extra authority: the DO
      // instance was already selected by idFromName above, and every
      // dashboard session is validated against that same instance's own
      // dashboard_sessions table regardless of what this segment says.
      forwardUrl.pathname = `/dashboard/${workspaceId}${parts.length > 2 ? "/" + parts.slice(2).join("/") : ""}`;
      return stub.fetch(new Request(forwardUrl, request));
    }

    if (parts.length !== 3) return new Response("not found", { status: 404 });
    const [route, workspaceId, token] = parts;
    if (!["link", "local"].includes(route)) return new Response("not found", { status: 404 });
    if (!isValidWorkspaceId(workspaceId)) return new Response("not found", { status: 404 });

    if (!checkOrigin(request)) {
      return new Response("forbidden", { status: 403 });
    }

    const doId = env.BRIDGE_DO.idFromName(workspaceId);
    const stub = env.BRIDGE_DO.get(doId);

    // Forward as /<route>/<token> — the Durable Object still needs the
    // token (to check it against its own stored secret), just not the
    // workspace_id (that already *is* which instance it is).
    const forwardUrl = new URL(request.url);
    forwardUrl.pathname = `/${route}/${token}`;
    return stub.fetch(new Request(forwardUrl, request));
  },
};

async function handleAdminRoute(request, env, adminToken) {
  if (!env.ADMIN_TOKEN || !constantTimeEqual(adminToken, env.ADMIN_TOKEN)) {
    return new Response("not found", { status: 404 });
  }
  if (!checkOrigin(request)) return new Response("forbidden", { status: 403 });
  if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });

  // Peek at workspace_id (size-capped, same as any other body) from a clone
  // so the real body — still fully intact — can be forwarded to the target
  // Durable Object, which reads it again itself.
  const peeked = await readJsonWithLimit(request.clone(), MAX_REQUEST_BYTES);
  if (peeked.tooLarge) return new Response("payload too large", { status: 413 });
  if (peeked.parseError || !peeked.value) return new Response("bad request", { status: 400 });
  if (
    [
      "provision_hub",
      "register_workspace",
      "unregister_workspace",
      "rotate_hub",
      "hub_browser_settings_get",
      "hub_browser_settings_set",
      "hub_owner_token_get",
    ].includes(peeked.value.op)
  ) {
    const hub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(HUB_DO_NAME));
    const forwardUrl = new URL(request.url);
    forwardUrl.pathname = "/admin";
    return hub.fetch(new Request(forwardUrl, request));
  }

  const workspaceId = peeked.value.workspace_id;
  if (typeof workspaceId !== "string" || !isValidWorkspaceId(workspaceId)) {
    return new Response("bad request", { status: 400 });
  }

  const doId = env.BRIDGE_DO.idFromName(workspaceId);
  const stub = env.BRIDGE_DO.get(doId);
  const forwardUrl = new URL(request.url);
  forwardUrl.pathname = "/admin";
  return stub.fetch(new Request(forwardUrl, request));
}

// stableGizmoId/parseProjectUrl/parseConversationUrl/areSameProject moved to
// bridge-admin.js (admin/settings domain owns the browser Project/
// conversation URL parsing) — see BridgeDO's parseProjectUrl/
// parseConversationUrl/areSameProject thin delegates below for how
// the dashboard domain (bridge-dashboard.js) reaches them as injected
// capabilities.

function randomHex(bytes) {
  const arr = new Uint8Array(bytes);
  crypto.getRandomValues(arr);
  return [...arr].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ---------------------------------------------------------------------------
// OAuth resource-server + authorization-server scaffolding
// (docs/plans/oauth-mcp-authentication.md, Phases 1-2): discovery metadata,
// 401 Bearer challenges, and now a real Authorization Code + PKCE + refresh
// token issuer on the new secret-free /mcp and /mcp/<workspace_id> resource
// URLs. OAuth state (authorization codes, access/refresh tokens) lives in
// whichever Durable Object owns the resource — the hub DO for /mcp, the
// per-workspace DO for /mcp/<workspace_id> — resolved via
// resolveOAuthResource() and reached only through internal-only DO routes
// (oauth-authorize/oauth-token/oauth-validate/oauth-mcp/oauth-hub-mcp; see
// BridgeDO.fetch), never exposed at a public URL directly. The JSON-RPC
// handlers remain separate from OAuth routing.
// ---------------------------------------------------------------------------

/** Parses an OAuth `resource` parameter (RFC 8707) into the Durable Object
 *  that owns it. Only this Worker's own canonical resource URLs are valid:
 *  "<origin>/mcp" (hub DO) or "<origin>/mcp/<workspace_id>" (that workspace's
 *  DO) — same-origin, no query/fragment, exact path shape. Anything else
 *  (wrong origin, unknown path, trailing slash, etc.) is `invalid_target`. */
function resolveOAuthResource(resourceParam, requestUrl) {
  let resourceUrl;
  try {
    resourceUrl = new URL(resourceParam);
  } catch {
    return { error: "invalid_target" };
  }
  const origin = new URL(requestUrl).origin;
  if (resourceUrl.origin !== origin || resourceUrl.search || resourceUrl.hash) return { error: "invalid_target" };

  const parts = resourceUrl.pathname.split("/").filter(Boolean);
  if (parts.length === 1 && parts[0] === "mcp") {
    return { workspaceId: undefined, resource: `${origin}/mcp`, doName: HUB_DO_NAME };
  }
  if (parts.length === 2 && parts[0] === "mcp" && isValidWorkspaceId(parts[1])) {
    return { workspaceId: parts[1], resource: `${origin}/mcp/${parts[1]}`, doName: parts[1] };
  }
  return { error: "invalid_target" };
}

async function sha256Hex(value) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// pkceChallengeFromVerifier/isValidPkceChallenge/isValidPkceVerifier/
// isValidRedirectUri/normalizeOAuthScope/isValidOAuthState/isValidOAuthScope
// and the OAUTH_STATE_MAX_BYTES/OAUTH_SCOPE_MAX_BYTES/
// OAUTH_REDIRECT_URI_MAX_BYTES/OAUTH_SCOPE_TOKEN_RE constants moved to
// bridge-oauth.js (Phase 2C) — they were only ever used by the
// BridgeDO-resident OAuth methods that moved with them. oauthError and
// parseOAuthForm moved to worker-oauth-http.js instead, since the top-level
// route handlers just below still need them too.

/** Only a syntactically valid "Bearer <token>" header yields a token.
 *  `attempted` is true whenever an Authorization header was present at all
 *  (well-formed or not), so callers can tell "no credential offered" (no
 *  error param on the 401) apart from "a credential was offered and
 *  rejected" (RFC 6750 error="invalid_token"). */
function extractBearerToken(request) {
  const header = request.headers.get("authorization");
  if (!header) return { token: null, attempted: false };
  const match = /^Bearer\s+(\S+)$/i.exec(header.trim());
  if (!match) return { token: null, attempted: true };
  return { token: match[1], attempted: true };
}

/** Hashes the presented bearer token and asks the DO that owns
 *  `expectedResource` to look it up (internal-only "/oauth-validate" route —
 *  see BridgeDO.handleOAuthValidate). The raw token itself never leaves this
 *  function; only its SHA-256 hash crosses the DO boundary. */
async function validateAccessToken(token, expectedResource, env) {
  const resolved = resolveOAuthResource(expectedResource, expectedResource);
  if (resolved.error) return { valid: false };

  const tokenHash = await sha256Hex(token);
  const stub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(resolved.doName));
  const forwardUrl = new URL(expectedResource);
  forwardUrl.pathname = "/oauth-validate";
  const res = await stub.fetch(
    new Request(forwardUrl, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ tokenHash, resource: expectedResource }),
    }),
  );
  if (res.status !== 200) return { valid: false };
  try {
    return await res.json();
  } catch {
    return { valid: false };
  }
}

function oauthUnauthorized(resourceMetadataUrl, { invalidToken = false } = {}) {
  const params = [`resource_metadata="${resourceMetadataUrl}"`];
  if (invalidToken) params.unshift(`error="invalid_token"`);
  return new Response(null, { status: 401, headers: { "www-authenticate": `Bearer ${params.join(", ")}` } });
}

const HTML_ESCAPES = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (c) => HTML_ESCAPES[c]);
}

/** The GET /oauth/authorize consent form (see
 *  BridgeDO.renderOAuthAuthorizeForm): a plain, dependency-free HTML page —
 *  no framework, no external script/style. Every already-validated OAuth
 *  parameter round-trips as a hidden field so the POST submission (handled
 *  by BridgeDO.processOAuthAuthorizePost, the same code path a
 *  non-interactive POST caller uses) re-validates them identically; the only
 *  new field is the resource-owner's token, entered here and never
 *  pre-filled or echoed anywhere. */
function renderOAuthConsentHtml({ resource, clientId, redirectUri, responseType, codeChallenge, codeChallengeMethod, state, scope }) {
  const hidden = (name, value) => `<input type="hidden" name="${escapeHtml(name)}" value="${escapeHtml(value)}">`;
  const hiddenFields = [
    hidden("resource", resource),
    hidden("client_id", clientId),
    hidden("redirect_uri", redirectUri),
    hidden("response_type", responseType),
    hidden("code_challenge", codeChallenge),
    hidden("code_challenge_method", codeChallengeMethod),
    state !== null ? hidden("state", state) : "",
    scope ? hidden("scope", scope) : "",
  ]
    .filter(Boolean)
    .join("\n");

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Authorize gpt-worker</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px;
    background: #f5f5f7;
    color: #1d1d1f;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }
  .card {
    width: 100%;
    max-width: 420px;
    background: #fff;
    border: 1px solid #e5e5e7;
    border-radius: 14px;
    padding: 28px;
  }
  h1 { font-size: 20px; margin: 0 0 16px; }
  .meta { font-size: 14px; color: #6e6e73; line-height: 1.5; margin: 0 0 8px; word-break: break-all; }
  .meta strong { color: inherit; font-weight: 600; }
  label { display: block; font-size: 13px; font-weight: 600; margin: 20px 0 6px; }
  input[type="password"] {
    width: 100%;
    padding: 10px 12px;
    font-size: 15px;
    border: 1px solid #d2d2d7;
    border-radius: 8px;
    background: #fff;
    color: inherit;
  }
  button {
    width: 100%;
    margin-top: 16px;
    padding: 11px 16px;
    font-size: 15px;
    font-weight: 600;
    color: #fff;
    background: #0071e3;
    border: none;
    border-radius: 8px;
    cursor: pointer;
  }
  button:hover { background: #0077ed; }
  .note { font-size: 12px; color: #86868b; margin-top: 16px; line-height: 1.4; }
  @media (prefers-color-scheme: dark) {
    body { background: #1c1c1e; color: #f5f5f7; }
    .card { background: #2c2c2e; border-color: #3a3a3c; }
    input[type="password"] { background: #1c1c1e; border-color: #48484a; }
  }
</style>
</head>
<body>
<div class="card">
<h1>Authorize access</h1>
<p class="meta"><strong>${escapeHtml(clientId)}</strong> is requesting access to<br><strong>${escapeHtml(resource)}</strong></p>
<p class="meta">Redirect URI: ${escapeHtml(redirectUri)}</p>
${scope ? `<p class="meta">Scope: ${escapeHtml(scope)}</p>` : ""}
<form method="post" action="/oauth/authorize">
${hiddenFields}
<label for="owner_token">gpt-worker owner token</label>
<input type="password" id="owner_token" name="owner_token" autocomplete="off" autofocus required>
<button type="submit">Authorize</button>
</form>
<p class="note">Only enter this token if you recognize and trust the client above — it grants access to your gpt-worker workspace.</p>
</div>
</body>
</html>
`;

  return new Response(html, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "referrer-policy": "no-referrer",
      // No form-action directive: this form's own action is hardcoded
      // (never attacker-controlled), but *after* that same-origin POST
      // succeeds, the server sends a 302 to the caller-supplied
      // redirect_uri — a different origin by design, already validated
      // server-side (isValidRedirectUri / registered-client exact match).
      // Modern browsers apply form-action to that post-submission redirect
      // too, not just the form's own action attribute, so form-action
      // 'self' here doesn't add security — it silently breaks the OAuth
      // redirect (observed live: clicking "Authorize" did nothing, because
      // the browser blocked following the 302 to chatgpt.com).
      "content-security-policy": "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'",
    },
  });
}

/** Handles the secret-free OAuth MCP resource routes ("/mcp" and
 *  "/mcp/<workspace_id>"): Bearer-authenticates the request against the
 *  owning DO's issued access tokens, then forwards the original request
 *  (still unread here — its JSON-RPC body is parsed DO-side) into that DO's
 *  internal oauth-mcp/oauth-hub-mcp route, which reuses the existing
 *  handleMcpRequest/handleHubMcpRequest JSON-RPC handlers unchanged. */
async function handleOAuthMcpResource(request, env, workspaceId) {
  if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });
  if (!checkOrigin(request)) return new Response("forbidden", { status: 403 });

  const metadataUrl = oauthProtectedResourceMetadataUrl(request.url, workspaceId);
  const { token, attempted } = extractBearerToken(request);
  if (!token) return oauthUnauthorized(metadataUrl, { invalidToken: attempted });

  const resource = oauthResourceUrl(request.url, workspaceId);
  const result = await validateAccessToken(token, resource, env);
  if (!result.valid) return oauthUnauthorized(metadataUrl, { invalidToken: true });

  const doName = workspaceId ? workspaceId : HUB_DO_NAME;
  const stub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(doName));
  const forwardUrl = new URL(request.url);
  forwardUrl.pathname = workspaceId ? "/oauth-mcp" : "/oauth-hub-mcp";
  return stub.fetch(new Request(forwardUrl, request));
}

/** GET/POST /oauth/authorize, POST /oauth/token, POST /oauth/register: pick
 *  `resource` from the query string (GET) or a cloned body (POST — same
 *  pattern as handleAdminRoute) to pick the owning DO, then forward the
 *  original, still-unread request into it. Credentials (owner_token / codes
 *  / refresh tokens) travel only in a POST body, never in the URL these
 *  functions build; GET /oauth/authorize itself carries no credential (see
 *  BridgeDO.renderOAuthAuthorizeForm). */
async function handleOAuthAuthorizeRoute(request, env) {
  if (request.method !== "GET" && request.method !== "POST") {
    return new Response(null, { status: 405, headers: { allow: "GET, POST" } });
  }
  // No Origin/Referer check here, unlike the other OAuth/MCP routes: this
  // endpoint has no ambient credential for a cross-site page to ride along
  // on (no cookie/session — owner_token only ever travels because the user
  // typed it into this page's own form), so Origin gating adds no real CSRF
  // protection, only false positives. Real browsers are inconsistent about
  // what Origin (if any — including the literal string "null") they send on
  // this same-origin form POST, which is exactly what broke it before.

  let resourceParam = "";
  if (request.method === "GET") {
    resourceParam = new URL(request.url).searchParams.get("resource") || "";
  } else {
    const parsed = await parseOAuthForm(request.clone(), MAX_REQUEST_BYTES);
    if (parsed.tooLarge) return oauthError("invalid_request", "payload too large", 413);
    if (parsed.unsupportedMediaType) return oauthError("invalid_request", "expected application/x-www-form-urlencoded", 415);
    resourceParam = parsed.params.get("resource") || "";
  }

  const resolved = resolveOAuthResource(resourceParam, request.url);
  if (resolved.error) return oauthError(resolved.error, "resource must be this server's /mcp or /mcp/<workspace_id>", 400);
  const stub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(resolved.doName));
  const forwardUrl = new URL(request.url);
  forwardUrl.pathname = "/oauth-authorize";
  return stub.fetch(new Request(forwardUrl, request));
}

async function handleOAuthTokenRoute(request, env) {
  if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });
  // No Origin check — same reasoning as handleOAuthAuthorizeRoute. The
  // credential here is `code`+`code_verifier` (PKCE) or a refresh token,
  // never a cookie/session, so there's no ambient authority for Origin
  // gating to protect against. A real OAuth client's token exchange can
  // legitimately come from any origin (its own backend, a browser context
  // on a domain we can't enumerate in advance) — Origin-checking this route
  // only produces false-positive 403s, not real protection.
  const parsed = await parseOAuthForm(request.clone(), MAX_REQUEST_BYTES);
  if (parsed.tooLarge) return oauthError("invalid_request", "payload too large", 413);
  if (parsed.unsupportedMediaType) return oauthError("invalid_request", "expected application/x-www-form-urlencoded", 415);
  const resolved = resolveOAuthResource(parsed.params.get("resource") || "", request.url);
  if (resolved.error) return oauthError(resolved.error, "resource must be this server's /mcp or /mcp/<workspace_id>", 400);
  const stub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(resolved.doName));
  const forwardUrl = new URL(request.url);
  forwardUrl.pathname = "/oauth-token";
  return stub.fetch(new Request(forwardUrl, request));
}

/** RFC 7591-style Dynamic Client Registration. Unlike every other OAuth
 *  route here, this is NOT resource-scoped: a real DCR client (ChatGPT, the
 *  MCP SDK) POSTs plain client metadata with no `resource` field, so this
 *  can't route by resource like handleOAuthAuthorizeRoute/handleOAuthTokenRoute
 *  do. Client records are instead kept globally in the hub DO — every
 *  registration goes there regardless of which resource(s) the client will
 *  later request, and any resource-owning DO looks a client_id up from the
 *  hub via BridgeDO.getOAuthClient() (see there for why). */
async function handleOAuthRegisterRoute(request, env) {
  if (request.method !== "POST") return new Response(null, { status: 405, headers: { allow: "POST" } });
  // No Origin check — DCR is, by design, meant to be callable by any OAuth
  // client software from anywhere (that's the point of *dynamic*
  // registration); there's no ambient credential here at all, so Origin
  // gating would only ever produce false positives, never real protection.
  const stub = env.BRIDGE_DO.get(env.BRIDGE_DO.idFromName(HUB_DO_NAME));
  const forwardUrl = new URL(request.url);
  forwardUrl.pathname = "/oauth-register";
  return stub.fetch(new Request(forwardUrl, request));
}

/** Serves RFC 9728 Protected Resource Metadata and OAuth Authorization
 *  Server Metadata under /.well-known/. Public: no Origin/token gating. */
function handleOAuthMetadataRoute(request, parts) {
  if (request.method !== "GET") return new Response(null, { status: 405, headers: { allow: "GET" } });

  const [, kind, ...rest] = parts;
  if (kind === "oauth-protected-resource") {
    if (rest.length === 0) return json(oauthProtectedResourceMetadata(request.url));
    if (rest.length === 1 && rest[0] === "mcp") return json(oauthProtectedResourceMetadata(request.url));
    if (rest.length === 2 && rest[0] === "mcp") {
      const workspaceId = rest[1];
      if (!isValidWorkspaceId(workspaceId)) return new Response("not found", { status: 404 });
      return json(oauthProtectedResourceMetadata(request.url, workspaceId));
    }
    return new Response("not found", { status: 404 });
  }
  if (kind === "oauth-authorization-server" && rest.length === 0) {
    return json(oauthAuthorizationServerMetadata(request.url));
  }
  return new Response("not found", { status: 404 });
}

// ---------------------------------------------------------------------------
// Durable Object: queue + WebSocket relay.
// ---------------------------------------------------------------------------

export class BridgeDO {
  constructor(ctx, env) {
    this.ctx = ctx;
    this.env = env;
    this.sql = ctx.storage.sql;

    initializeBridgeSchema(this.sql);

    // Protocol/queue domain (INIT/EXECUTED/PLAN/DONE/BLOCKED + task history —
    // see bridge-protocol.js's own header for its full method list and the
    // dependency/capability matrix it follows). Constructed once here and
    // reused by every thin BridgeDO delegate below; the two capabilities it
    // receives are its only cross-domain dependencies (admin/settings'
    // maxBodyBytes(), and transport's best-effort plan_pushed notification
    // via callLocal — never a generic callLocal handed through, and never a
    // direct import of another bridge-*.js domain module).
    this.protocol = createBridgeProtocol({
      sql: this.sql,
      maxBodyBytes: () => this.maxBodyBytes(),
      notifyPlanPushed: (messageId) => this.callLocal("plan_pushed", { message_id: messageId }),
      toolOk,
      toolError,
    });

    // Admin/settings/registry domain (secrets, provisioning, hub registry,
    // per-workspace settings/guidance — see bridge-admin.js's own header for
    // its full method list and the dependency/capability matrix it follows).
    // Constructed once here and reused by every thin BridgeDO delegate
    // below. Its cross-domain capabilities are all narrow callbacks, never a
    // direct import of another bridge-*.js domain module: token generation
    // reuses this file's own randomHex, and wiping/revoking protocol/OAuth/
    // dashboard state on deprovision or token rotation is delegated back to
    // this file's own methods (clearProtocolState, revokeAllOAuthTokens,
    // clearOAuthState, revokeAllDashboardSessions) rather than admin ever
    // touching those tables itself. revokeOAuthTokens/clearOAuthState below
    // stay lazy callbacks onto this file's own same-named methods (not
    // straight onto this.oauth) — those methods are thin delegates onto
    // this.oauth themselves (see below), and this.oauth isn't constructed
    // yet at this point in the constructor; by the time either callback is
    // actually invoked at runtime, this.oauth always is.
    this.admin = createBridgeAdmin({
      sql: this.sql,
      generateToken: () => randomHex(32),
      maxAdminRequestBytes: MAX_REQUEST_BYTES,
      clearProtocolState: () => this.clearProtocolState(),
      revokeOAuthTokens: () => this.revokeAllOAuthTokens(),
      clearOAuthState: () => this.clearOAuthState(),
      revokeDashboardSessions: () => this.revokeAllDashboardSessions(),
    });

    // OAuth authorization-server + resource-token domain (authorization
    // codes, access/refresh tokens, DCR clients — see bridge-oauth.js's own
    // header for its full method list and the dependency/capability matrix
    // it follows). Constructed once here and reused by every thin BridgeDO
    // delegate below. Its cross-domain capabilities are all narrow
    // callbacks, never a direct import of another bridge-*.js domain
    // module or a raw env/BRIDGE_DO handle: owner-token comparison and
    // hub-instance detection reuse this file's own checkToken/getSecret
    // (bridge-admin.js state, reached the same way every other BridgeDO
    // caller reaches them), hex/hash generation reuse this file's own
    // randomHex/sha256Hex, the DCR rate-limit bucket reuses this file's own
    // generic rateLimit(), and the cross-DO client-lookup callback below is
    // the only place bridge-oauth.js's cross-DO need (a workspace DO asking
    // the hub DO for a registered client) touches env.BRIDGE_DO — inside
    // this file, never inside bridge-oauth.js itself.
    this.oauth = createBridgeOAuth({
      sql: this.sql,
      checkHubOwnerToken: (token) => this.checkToken("hub_gpt_token", token),
      checkWorkspaceOwnerToken: (token) => this.checkToken("gpt_token", token),
      hasHubOwnerSecret: () => this.getSecret("hub_gpt_token") !== null,
      lookupHubOAuthClient: async (clientId, resource) => {
        const hub = this.env.BRIDGE_DO.get(this.env.BRIDGE_DO.idFromName(HUB_DO_NAME));
        const forwardUrl = new URL(resource);
        forwardUrl.pathname = "/oauth-client-lookup";
        const res = await hub.fetch(
          new Request(forwardUrl, {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ clientId }),
          }),
        );
        if (res.status !== 200) return null;
        try {
          const data = await res.json();
          return data.client || null;
        } catch {
          return null;
        }
      },
      checkOAuthRegisterRateLimit: () => this.rateLimit("oauth-register", 10),
      generateHex: (bytes) => randomHex(bytes),
      hashValue: (value) => sha256Hex(value),
      renderConsentHtml: (fields) => renderOAuthConsentHtml(fields),
      maxOAuthRequestBytes: MAX_REQUEST_BYTES,
    });

    // Local transport domain (the /link WebSocket, /local CLI dispatch, the
    // pending-RPC table, and rate limiting — see bridge-transport.js's own
    // header for its full method list and the dependency/capability matrix
    // it follows). Constructed once here and reused by every thin BridgeDO
    // delegate below, so `callLocal` (which registers a pending RPC) and
    // `webSocketMessage`/`webSocketClose`/`webSocketError` (which resolve
    // it) always share the one `pending` map this object owns. Its
    // cross-domain capabilities are all narrow callbacks, never a direct
    // import of another bridge-*.js domain module or a raw sql/env handle:
    // token checks reuse this file's own checkToken (bridge-admin.js state),
    // and every /local op routes onto the same-named BridgeDO delegate
    // (protocol/admin operations), each a lazy arrow so this constructor's
    // ordering never matters and the transport never sees those domain
    // objects themselves. `ctx` itself is handed over only because the
    // transport owns the WebSocket lifecycle (getWebSockets/acceptWebSocket).
    this.transport = createBridgeTransport({
      ctx,
      checkLinkToken: (token) => this.checkToken("link_token", token),
      checkCliToken: (token) => this.checkToken("cli_token", token),
      maxRequestBytes: () => this.maxRequestBytes(),
      pendingMessageCounts: () => this.protocol.pendingMessageCounts(),
      localOperations: {
        enqueue: (body) => this.localEnqueue(body),
        start_task: (body) => this.localStartTask(body),
        report_task: (body) => this.localReportTask(body),
        // The read window is an MCP-domain concern and the protocol domain may
        // not import it (one-way dependency), so the two are joined here in
        // the composition root. The CLI needs it to show how much of the
        // window is left without holding its own copy of the constant.
        active_task: () => ({ task: this.taskView(this.activeTask()), taskWindow: this.taskWindowInfo() }),
        migrate_legacy_state: (body) => this.localMigrateLegacyState(body),
        settings_get: () => this.localSettingsGet(),
        settings_set: (body) => this.localSettingsSet(body),
        browser_settings_get: () => this.localBrowserSettingsGet(),
        browser_settings_set: (body) => this.localBrowserSettingsSet(body),
        max_body_bytes_get: () => this.localMaxBodyBytesGet(),
        max_body_bytes_set: (body) => this.localMaxBodyBytesSet(body),
        guidance_set: (body) => this.localGuidanceSet(body),
        guidance_get: () => this.workspaceGuidance(),
        guidance_clear: () => this.localGuidanceClear(),
        poll: (body) => this.localPoll(body),
        ack: (body) => this.localAck(body),
        list: (body) => this.localList(body),
        discard_task: (body) => this.localDiscardTask(body),
        discard: (body) => this.localDiscard(body),
        complete_task: (body) => this.localCompleteTask(body),
        continue_task: (body) => this.localContinueTask(body),
      },
    });

    // MCP dispatch + tool invocation domain (dedicated/shared connector
    // variants, list_workspaces, the binding-only /hub relay — see
    // bridge-mcp.js's own header for its full method list and the
    // dependency/capability matrix it follows). Constructed once here and
    // reused by every thin BridgeDO delegate below. Its cross-domain
    // capabilities are all narrow, purpose-fixed callbacks, never a direct
    // import of another bridge-*.js domain module: protocol/admin reads go
    // through this file's own same-named delegates, workspace-tool relay goes
    // through callLocal, the oauth-mcp rate-limit bucket goes through
    // rateLimit, and the only place the hub's tool relay touches
    // env.BRIDGE_DO (the binding-only /hub call, forwarding just the tool
    // name/arguments — never a hub credential or session) is the callback
    // below, inside this file, never inside bridge-mcp.js itself.
    this.mcp = createBridgeMcp({
      queueNext: (taskId) => this.queueNext(taskId),
      queueSubmit: (args) => this.queueSubmit(args),
      queueSetTitle: (args) => this.queueSetTitle(args),
      taskHistory: (args) => this.taskHistory(args),
      activeTask: () => this.activeTask(),
      workspaceGuidance: () => this.workspaceGuidance(),
      registeredWorkspaces: () => this.registeredWorkspaces(),
      maxWorkspaceRequestBytes: () => this.maxRequestBytes(),
      relayWorkspaceTool: (name, params) => this.callLocal(name, params),
      allowOAuthMcpRequest: (useHubHandler) => this.rateLimit(useHubHandler ? "oauth-hub-mcp" : "oauth-mcp", 60),
      relayHubToolToWorkspace: async (workspaceId, name, args) => {
        const stub = this.env.BRIDGE_DO.get(this.env.BRIDGE_DO.idFromName(workspaceId));
        const response = await stub.fetch(new Request("https://gpt-worker.internal/hub", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ name, arguments: args }),
        }));
        return response.json();
      },
      maxSharedRequestBytes: MAX_REQUEST_BYTES_CEILING,
    });

    // Web dashboard domain (dashboard sessions, workspace dashboard, shared
    // hub dashboard, history/API operations, the binding-only
    // /hub-dashboard-relay — see bridge-dashboard.js's own header for its
    // full method list and the dependency/capability matrix it follows).
    // Constructed once here and reused by every thin BridgeDO delegate
    // below. Its cross-domain capabilities are all narrow, purpose-fixed
    // callbacks/scalars, never a direct import of another bridge-*.js domain
    // module or a raw env/BRIDGE_DO/ctx handle: every admin/protocol/
    // transport/OAuth dependency goes through this file's own same-named
    // delegates (lazy arrows, so this constructor's ordering never matters —
    // the delegates themselves already route to this.admin/this.protocol/
    // this.transport/this.oauth), and the two cross-DO callbacks below
    // (hub browser settings read, and the binding-only /hub-dashboard-relay
    // call) are the only places the dashboard's cross-DO needs touch
    // env.BRIDGE_DO — inside this file, never inside bridge-dashboard.js.
    // The relay callback forwards only the already-authorized operation
    // envelope (name/method/query/body); the hub session cookie and
    // hub_gpt_token are never forwarded to a workspace DO.
    this.dashboard = createBridgeDashboard({
      sql: this.sql,
      generateSessionToken: () => randomHex(32),
      hashSessionToken: (value) => sha256Hex(value),
      escapeHtmlValue: (value) => escapeHtml(value),
      checkResourceOwnerToken: (token) => this.checkResourceOwnerToken(token),
      hasSecrets: () => this.hasSecrets(),
      isHubInstance: () => this.isHubInstance(),
      workspaceGuidance: () => this.workspaceGuidance(),
      maxBodyBytes: () => this.maxBodyBytes(),
      maxRequestBytes: () => this.maxRequestBytes(),
      localMaxBodyBytesGet: () => this.localMaxBodyBytesGet(),
      localMaxBodyBytesSet: (body) => this.localMaxBodyBytesSet(body),
      localBrowserSettingsGet: () => this.localBrowserSettingsGet(),
      localBrowserSettingsSet: (body) => this.localBrowserSettingsSet(body),
      hubBrowserSettingsGet: () => this.hubBrowserSettingsGet(),
      hubBrowserSettingsSet: (body) => this.hubBrowserSettingsSet(body),
      localGuidanceSet: (body) => this.localGuidanceSet(body),
      localGuidanceClear: () => this.localGuidanceClear(),
      parseProjectUrl: (rawUrl) => this.parseProjectUrl(rawUrl),
      parseConversationUrl: (rawUrl) => this.parseConversationUrl(rawUrl),
      areSameProject: (projectInfo, conversationInfo) => this.areSameProject(projectInfo, conversationInfo),
      registeredWorkspaces: () => this.registeredWorkspaces(),
      activeTask: () => this.activeTask(),
      taskView: (task) => this.taskView(task),
      getTask: (taskId) => this.getTask(taskId),
      localAck: (body) => this.localAck(body),
      localDiscard: (body) => this.localDiscard(body),
      localDiscardTask: (body) => this.localDiscardTask(body),
      localStartTask: (body) => this.localStartTask(body),
      localCompleteTask: (body) => this.localCompleteTask(body),
      localContinueTask: (body) => this.localContinueTask(body),
      queryDashboardMessages: (args) => this.protocol.dashboardMessageRows(args),
      queryDashboardTasks: (args) => this.protocol.dashboardTaskRows(args),
      messageDirection: (messageId) => this.protocol.messageDirection(messageId),
      localStatus: () => this.localStatus(),
      consumeDashboardRateLimit: (bucket, maxPerMinute) => this.rateLimit(bucket, maxPerMinute),
      notifyDashboardTaskCreated: (taskId) => this.callLocal("dashboard_task_created", { taskId }),
      fetchHubBrowserSettings: async () => {
        try {
          const hub = this.env.BRIDGE_DO.get(this.env.BRIDGE_DO.idFromName(HUB_DO_NAME));
          const res = await hub.fetch(
            new Request("https://gpt-worker.internal/admin", {
              method: "POST",
              headers: { "content-type": "application/json" },
              body: JSON.stringify({ op: "hub_browser_settings_get" }),
            })
          );
          if (res.status !== 200) return null;
          return await res.json().catch(() => null);
        } catch {
          return null;
        }
      },
      fetchWorkspaceDashboardRelay: async (workspaceId, envelope) => {
        const stub = this.env.BRIDGE_DO.get(this.env.BRIDGE_DO.idFromName(workspaceId));
        return stub.fetch(
          new Request("https://gpt-worker.internal/hub-dashboard-relay", {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify(envelope),
          })
        );
      },
      openDashboardWebSocket: (args) => this.openDashboardWebSocket(args),
      broadcastDashboardEvent: (tag, payload) => this.broadcastDashboardEvent(tag, payload),
      closeDashboardSockets: (args) => this.closeDashboardSockets(args),
      maxFixedRequestBytes: MAX_REQUEST_BYTES,
      maxSharedRequestBytes: MAX_REQUEST_BYTES_CEILING,
      ackedMessageRetentionMs: RETENTION_MS,
      terminalTaskRetentionMs: TASK_RETENTION_MS,
    });

    ctx.blockConcurrencyWhile(async () => {
      const current = await ctx.storage.getAlarm();
      if (current === null) await ctx.storage.setAlarm(Date.now() + ALARM_INTERVAL_MS);
    });
  }

  async fetch(request) {
    const url = new URL(request.url);
    const parts = url.pathname.split("/").filter(Boolean);
    if (parts.length === 1 && parts[0] === "admin") return this.handleAdmin(request);
    if (parts.length === 1 && parts[0] === "hub") return this.handleHubRelay(request);
    // Internal-only, binding-call route used by the hub DO to relay one
    // authenticated hub-dashboard operation into this workspace's own
    // dashboard API dispatcher (see handleHubDashboardRelay/
    // hubDashboardRelay) — never routed here from a public URL (the
    // top-level Worker's fetch has no path shape that reaches it).
    if (parts.length === 1 && parts[0] === "hub-dashboard-relay") return this.handleHubDashboardRelay(request);
    if (parts.length === 1 && parts[0] === "hub-dashboard-invalidate") return this.handleHubDashboardInvalidation(request);
    // Web dashboard (docs/plans/queue-dashboard.md): forwarded here as
    // /dashboard/<workspace_id>[/...] — see the top-level routing comment.
    // Variable length (root shell, app.js, login/logout, api/*), so this
    // dispatches by prefix rather than the fixed part-count checks below.
    // "hub" is routed to the hub DO's own dashboard instead (see
    // handleHubDashboard) — a workspace DO's own instance is never reached
    // with workspaceId === "hub" through the top-level routing above.
    if (parts[0] === "dashboard" && parts.length >= 2) {
      if (parts[1] === "hub") return this.handleHubDashboard(request, parts.slice(2));
      return this.handleDashboard(request, parts[1], parts.slice(2));
    }
    // Internal-only OAuth routes: reachable exclusively through a
    // BRIDGE_DO binding call from the top-level Worker (see
    // handleOAuthAuthorizeRoute/handleOAuthTokenRoute/validateAccessToken/
    // handleOAuthMcpResource), never mapped to from a public URL there.
    if (parts.length === 1 && parts[0] === "oauth-authorize") return this.handleOAuthAuthorize(request);
    if (parts.length === 1 && parts[0] === "oauth-token") return this.handleOAuthToken(request);
    if (parts.length === 1 && parts[0] === "oauth-register") return this.handleOAuthRegister(request);
    if (parts.length === 1 && parts[0] === "oauth-client-lookup") return this.handleOAuthClientLookup(request);
    if (parts.length === 1 && parts[0] === "oauth-validate") return this.handleOAuthValidate(request);
    if (parts.length === 1 && parts[0] === "oauth-mcp") return this.handleOAuthMcpDispatch(request, false);
    if (parts.length === 1 && parts[0] === "oauth-hub-mcp") return this.handleOAuthMcpDispatch(request, true);
    if (parts.length !== 2) return new Response("not found", { status: 404 });
    const [route, token] = parts;
    if (route === "link") return this.handleLink(request, token);
    if (route === "local") return this.handleLocalRoute(request, token);
    return new Response("not found", { status: 404 });
  }

  // ======================= secrets (per-workspace tokens) =======================
  // Thin delegates onto the admin/settings/registry domain — see
  // bridge-admin.js's own header for the capability/dependency matrix this
  // extraction follows. Method names, argument shapes, and return values are
  // unchanged from before the extraction.

  getSecret(key) {
    return this.admin.getSecret(key);
  }

  setSecret(key, value) {
    return this.admin.setSecret(key, value);
  }

  hasSecrets() {
    return this.admin.hasSecrets();
  }

  checkToken(secretKey, token) {
    return this.admin.checkToken(secretKey, token);
  }

  // ======================= /admin : provisioning (this workspace's own DO) =======================

  async handleAdmin(request) {
    let op = null;
    if (request.method === "POST") {
      try {
        const peeked = await readJsonWithLimit(request.clone(), MAX_REQUEST_BYTES);
        if (peeked && !peeked.tooLarge && !peeked.parseError && peeked.value) {
          op = peeked.value.op;
        }
      } catch {}
    }

    const response = await this.admin.handleAdmin(request);

    if (op && response.ok) {
      let isSuccess = true;
      try {
        const data = await response.clone().json();
        if (data && data.error) {
          isSuccess = false;
        }
      } catch {
        isSuccess = false;
      }
      if (isSuccess) {
        if (op === "register_workspace" || op === "unregister_workspace") {
          this.notifyDashboardInvalidation("registry");
        } else if (op === "hub_browser_settings_set") {
          this.notifyDashboardInvalidation("settings");
        } else if (op === "deprovision" || op === "provision" || op === "migrate_default") {
          this.notifyDashboardInvalidation("activity");
        }
      }
    }

    return response;
  }

  hubBrowserSettingsGet() {
    return this.admin.hubBrowserSettingsGet();
  }

  hubBrowserSettingsSet(body) {
    const res = this.admin.hubBrowserSettingsSet(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("settings");
    }
    return res;
  }

  hubOwnerTokenGet() {
    return this.admin.hubOwnerTokenGet();
  }

  ownerTokenGet() {
    return this.admin.ownerTokenGet();
  }

  /** Irreversibly wipes this workspace's tokens, queue, task state and settings — its Server URL
   *  and CLI/link tokens 404 immediately afterward, same as if it had never
   *  been provisioned. Used by `gpt-worker remove`. There is no "undo": a
   *  workspace_id can be re-provisioned later, but that starts a fresh
   *  queue with fresh tokens, not a restore of what was here. Delegates to
   *  admin's deprovision(), which wipes secrets/settings itself and calls
   *  back into clearProtocolState()/clearOAuthState()/
   *  revokeAllDashboardSessions() below for the domains it doesn't own. */
  deprovision() {
    this.closeDashboardSockets();
    const res = this.admin.deprovision();
    this.notifyDashboardInvalidation("activity");
    return res;
  }

  /** Wipes every queued message and task row (bridge-protocol.js's
   *  clearProtocolState) — the narrow callback admin's deprovision() uses
   *  instead of touching msgs/tasks itself. */
  clearProtocolState() {
    return this.protocol.clearProtocolState();
  }

  /** Revokes every OAuth authorization code/access token/refresh token this
   *  DO has issued for its own resource — not the DCR client registry
   *  (oauth_clients), which is independent of any owner credential. Called
   *  when gpt_token/hub_gpt_token rotates, since that value doubles as the
   *  OAuth resource-owner credential (see checkResourceOwnerToken): a
   *  deliberate rotation (e.g. because it may have leaked) should also cut
   *  off OAuth grants already issued under the old value, not just block
   *  future /oauth-authorize calls. */
  revokeAllOAuthTokens() {
    return this.oauth.revokeAllOAuthTokens();
  }

  /** Wipes all OAuth server state for this DO — every issued authorization
   *  code, access token, refresh token, and (unlike revokeAllOAuthTokens()
   *  above) every registered DCR client too. Used only by admin's
   *  deprovision(), which removes the workspace entirely; a token rotation
   *  must not lose registered clients, so it uses revokeAllOAuthTokens()
   *  instead. */
  clearOAuthState() {
    return this.oauth.clearOAuthState();
  }

  /** Replaces one of this workspace's 3 tokens with a fresh random value.
   *  Only the named key changes; the other two (and every queued message)
   *  are untouched. Requires the workspace to already be provisioned. */
  rotateSecret(key) {
    if (key === "gpt_token") {
      this.revokeAllDashboardSessions();
      this.closeDashboardSockets();
    }
    return this.admin.rotateSecret(key);
  }

  /** Fresh workspace: generates all 3 tokens. Refuses if this workspace_id
   *  was already provisioned, so a routing collision (or a retried admin
   *  call) can never silently overwrite an existing workspace's tokens. */
  provision() {
    return this.admin.provision();
  }

  /** Creates the one token embedded in the single ChatGPT connector URL. */
  provisionHub() {
    return this.admin.provisionHub();
  }

  rotateHubToken() {
    return this.admin.rotateHubToken();
  }

  registerWorkspace(body) {
    const res = this.admin.registerWorkspace(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("registry");
    }
    return res;
  }

  unregisterWorkspace(body) {
    const res = this.admin.unregisterWorkspace(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("registry");
    }
    return res;
  }

  /** Adopts the exact token values from the pre-multi-tenant single-DO
   *  deployment (workspace_id "default") — never generates new ones, so
   *  the already-registered ChatGPT connector's tokens keep working once
   *  its Server URL gains the /default/ segment. */
  migrateDefault(body) {
    return this.admin.migrateDefault(body);
  }

  // ======================= browser Project/conversation URL helpers =======================
  // Thin delegates onto admin's pure parser/matcher (bridge-admin.js's
  // parseProjectUrl/parseConversationUrl/areSameProject), handed to the
  // dashboard domain (bridge-dashboard.js's dashboardSetBrowserSettings) as
  // injected capabilities rather than bridge-dashboard.js importing
  // bridge-admin.js directly.

  parseProjectUrl(rawUrl) {
    return this.admin.parseProjectUrl(rawUrl);
  }

  parseConversationUrl(rawUrl) {
    return this.admin.parseConversationUrl(rawUrl);
  }

  areSameProject(projectInfo, conversationInfo) {
    return this.admin.areSameProject(projectInfo, conversationInfo);
  }

  // ---- rate limiting (sliding window, best-effort across hibernation) ----
  // Thin delegates onto the local transport domain (bridge-transport.js),
  // which owns the rate-limit buckets and the pending-RPC table. The three
  // webSocket* methods are Cloudflare Durable Object runtime entrypoints
  // (WebSocket Hibernation API) and must stay defined on BridgeDO itself —
  // they only delegate.

  rateLimit(key, maxPerMinute) {
    return this.transport.rateLimit(key, maxPerMinute);
  }

  // ======================= /link : local bridge WebSocket =======================

  async handleLink(request, token) {
    const res = await this.transport.handleLink(request, token);
    if (res && res.status === 101) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  webSocketMessage(ws, message) {
    if (ws?.deserializeAttachment?.()?.kind === "dashboard") return;
    return this.transport.webSocketMessage(ws, message);
  }

  webSocketClose(ws, ...args) {
    if (ws?.deserializeAttachment?.()?.kind === "dashboard") return;
    const res = this.transport.webSocketClose(ws, ...args);
    this.notifyDashboardInvalidation("activity");
    return res;
  }

  webSocketError(ws, ...args) {
    if (ws?.deserializeAttachment?.()?.kind === "dashboard") return;
    const res = this.transport.webSocketError(ws, ...args);
    this.notifyDashboardInvalidation("activity");
    return res;
  }

  openDashboardWebSocket({ tag, attachment }) {
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair);
    this.ctx.acceptWebSocket(server, [tag]);
    if (server.serializeAttachment && attachment) {
      server.serializeAttachment(attachment);
    }
    return new Response(null, { status: 101, webSocket: client });
  }

  broadcastDashboardEvent(tag, payload) {
    const now = Date.now();
    const str = typeof payload === "string" ? payload : JSON.stringify(payload);
    for (const ws of this.ctx.getWebSockets(tag)) {
      const att = ws.deserializeAttachment ? ws.deserializeAttachment() : null;
      if (att && att.expiresAt && att.expiresAt < now) {
        try {
          ws.close(1008, "session expired");
        } catch {}
        continue;
      }
      try {
        ws.send(str);
      } catch {}
    }
  }

  closeDashboardSockets({ tag, sessionHash } = {}) {
    const tags = tag ? [tag] : ["dashboard-workspace", "dashboard-hub"];
    for (const t of tags) {
      for (const ws of this.ctx.getWebSockets(t)) {
        const att = ws.deserializeAttachment ? ws.deserializeAttachment() : null;
        if (!sessionHash || (att && att.sessionHash === sessionHash)) {
          try {
            ws.close(1008, "session revoked");
          } catch {}
        }
      }
    }
  }

  notifyDashboardInvalidation(scope) {
    if (this.isHubInstance()) {
      this.broadcastDashboardEvent("dashboard-hub", { type: "invalidate", scope });
      return;
    }
    this.broadcastDashboardEvent("dashboard-workspace", { type: "invalidate", scope });
    const workspaceId = this.ctx?.id?.name;
    if (workspaceId && this.env?.BRIDGE_DO) {
      try {
        const hub = this.env.BRIDGE_DO.get(this.env.BRIDGE_DO.idFromName(HUB_DO_NAME));
        const promise = hub.fetch(
          new Request("https://gpt-worker.internal/hub-dashboard-invalidate", {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ workspaceId, scope }),
          })
        ).catch(() => {});
        if (this.ctx?.waitUntil) {
          this.ctx.waitUntil(promise);
        }
      } catch {}
    }
  }

  async handleHubDashboardInvalidation(request) {
    return this.dashboard.handleHubDashboardInvalidation(request);
  }

  failAllPending() {
    return this.transport.failAllPending();
  }

  /** Send a request to the local bridge over the WS link and await its reply. */
  async callLocal(method, params) {
    return this.transport.callLocal(method, params);
  }

  // ======================= OAuth: authorization server + resource validation =======================
  // Thin delegates onto the OAuth authorization-server + resource-token
  // domain — see bridge-oauth.js's own header for the capability/dependency
  // matrix this extraction follows. Method names, argument shapes, and
  // return values are unchanged from before the extraction. Internal-only:
  // every method here is reached exclusively through the oauth-* routes in
  // BridgeDO.fetch, which are themselves reachable only via a BRIDGE_DO
  // binding call from the top-level Worker's
  // handleOAuthAuthorizeRoute/handleOAuthTokenRoute/validateAccessToken/
  // handleOAuthMcpResource — never from a public URL directly.

  /** A DO instance is either the hub (has hub_gpt_token, never gpt_token) or
   *  one workspace (has gpt_token, never hub_gpt_token) — provisionHub() and
   *  provision() are called on disjoint DO instances, so checking both keys
   *  here is sufficient without the caller having to tell us which one this
   *  is. */
  checkResourceOwnerToken(ownerToken) {
    return this.oauth.checkResourceOwnerToken(ownerToken);
  }

  /** GET/POST /oauth-authorize (internal). GET renders a minimal HTML
   *  consent form (a real OAuth client navigates the browser here); POST
   *  processes that form's submission — or a direct POST from a
   *  non-interactive caller — and, on success, issues a short-lived
   *  one-time authorization code. Resource-owner auth is this workspace's/
   *  the hub's own existing gpt token, submitted only as POST body field
   *  `owner_token` — never in the URL, query string, or redirect. */
  async handleOAuthAuthorize(request) {
    return this.oauth.handleOAuthAuthorize(request);
  }

  /** Shared by both the GET form-render path and the POST code-issuing
   *  path, so the two can never validate a request differently. Excludes
   *  `owner_token`, which only ever appears in a POST body and is checked
   *  separately by processOAuthAuthorizePost. Async because client lookup
   *  may be a cross-DO call (see getOAuthClient). */
  async validateOAuthAuthorizeRequest(fields) {
    return this.oauth.validateOAuthAuthorizeRequest(fields);
  }

  async renderOAuthAuthorizeForm(request) {
    return this.oauth.renderOAuthAuthorizeForm(request);
  }

  async processOAuthAuthorizePost(request) {
    return this.oauth.processOAuthAuthorizePost(request);
  }

  /** True only for the one dedicated hub DO instance (see the same disjoint-
   *  secret reasoning as checkResourceOwnerToken): it alone ever gets
   *  hub_gpt_token set, via provisionHub(). */
  isHubInstance() {
    return this.oauth.isHubInstance();
  }

  /** Reads a client_id's DCR record straight from this instance's own
   *  oauth_clients table. Only ever populated on the hub DO — see
   *  getOAuthClient for why — but harmless to expose on any instance. */
  getOAuthClientLocal(clientId) {
    return this.oauth.getOAuthClientLocal(clientId);
  }

  /** Registered-client metadata from DCR, or null for an unregistered
   *  client_id (Phase 2 compatibility clients). Client registrations are
   *  global — kept only in the hub DO's oauth_clients table (see
   *  handleOAuthRegisterRoute for why: a real DCR request carries no
   *  `resource` to route by) — so a workspace DO asks the hub DO over an
   *  internal binding call rather than checking its own (always-empty)
   *  copy of the table. `resource` supplies the origin for that internal
   *  call; it carries no other meaning here. */
  async getOAuthClient(clientId, resource) {
    return this.oauth.getOAuthClient(clientId, resource);
  }

  /** POST /oauth-client-lookup (internal, hub DO only): looks up one
   *  client_id for a resource-owning DO's getOAuthClient() cross-DO call. */
  async handleOAuthClientLookup(request) {
    return this.oauth.handleOAuthClientLookup(request);
  }

  /** POST /oauth-register (internal, reached only via the hub DO — see
   *  handleOAuthRegisterRoute): minimal RFC 7591-style Dynamic Client
   *  Registration. Public clients only (token_endpoint_auth_method=none, no
   *  client secret) — this Worker never authenticates an OAuth client
   *  itself, only the resource owner (see checkResourceOwnerToken). Accepts
   *  (and ignores beyond validating/echoing) the standard optional metadata
   *  fields grant_types/response_types/application_type a real DCR client
   *  such as ChatGPT or the MCP SDK sends, so registration doesn't require
   *  any gpt-worker-specific field. */
  async handleOAuthRegister(request) {
    return this.oauth.handleOAuthRegister(request);
  }

  /** POST /oauth-token (internal). Dispatches on `grant_type`. */
  async handleOAuthToken(request) {
    return this.oauth.handleOAuthToken(request);
  }

  async exchangeOAuthAuthorizationCode(params) {
    return this.oauth.exchangeOAuthAuthorizationCode(params);
  }

  async exchangeOAuthRefreshToken(params) {
    return this.oauth.exchangeOAuthRefreshToken(params);
  }

  async issueOAuthTokenFamily(args) {
    return this.oauth.issueOAuthTokenFamily(args);
  }

  revokeOAuthFamily(familyId) {
    return this.oauth.revokeOAuthFamily(familyId);
  }

  /** POST /oauth-validate (internal, JSON body {tokenHash, resource}). Used
   *  only by the top-level validateAccessToken() — never exposed publicly,
   *  so the raw bearer token itself never needs to reach here, only its
   *  hash. */
  async handleOAuthValidate(request) {
    return this.oauth.handleOAuthValidate(request);
  }

  /** POST /oauth-mcp or /oauth-hub-mcp (internal). Reached only after
   *  handleOAuthMcpResource has Bearer-authenticated the caller. Thin
   *  delegates onto the MCP dispatch domain (bridge-mcp.js) — see its own
   *  header for the capability/dependency matrix this extraction follows. */
  async handleOAuthMcpDispatch(request, useHubHandler) {
    return this.mcp.handleOAuthMcpDispatch(request, useHubHandler);
  }

  async handleHubMcpRequest(rpc) {
    return this.mcp.handleHubMcpRequest(rpc);
  }

  registeredWorkspaces() {
    return this.admin.registeredWorkspaces();
  }

  async handleHubToolCall(id, params) {
    return this.mcp.handleHubToolCall(id, params);
  }

  /** Internal, binding-only entry point used by the hub to preserve the
   * existing workspace task queues and read gating. Reachable only from the
   * hub's own handleHubToolCall relay, so reaching here always means the
   * shared connector. */
  async handleHubRelay(request) {
    return this.mcp.handleHubRelay(request);
  }

  async handleMcpRequest(rpc) {
    return this.mcp.handleMcpRequest(rpc);
  }

  async handleToolCall(id, params) {
    return this.mcp.handleToolCall(id, params);
  }

  async invokeTool(name, args = {}, options = {}) {
    return this.mcp.invokeTool(name, args, options);
  }

  // ---- postbox: to_gpt / to_local queues, backed by SQLite ----

  /** taskId is optional: when given (e.g. the user's message named a
   *  specific task), only that task's oldest undelivered message is
   *  eligible — no fallback to a different task if it isn't there, since
   *  silently substituting one would be more confusing than {empty:true}. */
  queueNext(taskId) {
    const res = this.protocol.queueNext(taskId);
    if (res && !res.empty && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  /**
   * Persist the Web-generated label for a task only during the active INIT
   * lease. It intentionally does not advance protocol state, create queue
   * messages, or touch updated_at: this is presentation metadata, not a
   * PLAN/DONE/BLOCKED transition.
   */
  queueSetTitle(args) {
    const res = this.protocol.queueSetTitle(args);
    if (res && !res.isError && res.structuredContent?.idempotent === false) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  queueSubmit(args) {
    const res = this.protocol.queueSubmit(args);
    if (res && !res.isError && (res.ok !== false)) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  /** Past tasks that reached a terminal state (DONE/BLOCKED), newest first —
   *  lets GPT orient itself in a fresh conversation without depending
   *  solely on this Project's own (less reliable) memory. Lives entirely
   *  in this queue's SQLite, so unlike the workspace tools it works even
   *  while the local bridge is offline. Returns terminal tasks (DONE/BLOCKED)
   *  that have been acknowledged/finalized by the local side. */
  taskHistory(args) {
    return this.protocol.taskHistory(args);
  }

  getTask(taskId) {
    return this.protocol.getTask(taskId);
  }

  activeTask() {
    return this.protocol.activeTask();
  }

  taskView(task) {
    return this.protocol.taskView(task);
  }

  isActiveTaskWindow() {
    return this.mcp.isActiveTaskWindow();
  }

  taskWindowState() {
    return this.mcp.taskWindowState();
  }

  taskWindowInfo() {
    return this.mcp.taskWindowInfo();
  }

  workspaceGuidance() {
    return this.admin.workspaceGuidance();
  }

  // ======================= /dashboard : Web dashboard =======================
  // Thin delegates onto the Web dashboard domain (workspace dashboard, shared
  // hub dashboard, dashboard sessions, history/API operations, and the
  // binding-only /hub-dashboard-relay) — see bridge-dashboard.js's own
  // header for the capability/dependency matrix this extraction follows.
  // Method names, argument shapes, and return values are unchanged from
  // before the extraction. BridgeDO.fetch's routing and alarm() stay here as
  // the DO runtime's own entrypoints; they only call these delegates.
  //
  // dashboardApiDispatch below is a compatibility facade only (kept so the
  // BridgeDO method surface stays stable across the extraction): it is not
  // routed from any public URL and adds no caller. The one real dispatcher
  // lives in bridge-dashboard.js and performs no auth itself; its only
  // internal callers are handleDashboardApi (public workspace route) and
  // handleHubDashboardRelay (binding-only hub relay). Do not add a third
  // caller of this delegate.

  revokeAllDashboardSessions() {
    return this.dashboard.revokeAllDashboardSessions();
  }

  dashboardOverview() {
    return this.dashboard.dashboardOverview();
  }

  dashboardMessages(params) {
    return this.dashboard.dashboardMessages(params);
  }

  dashboardTasks(params) {
    return this.dashboard.dashboardTasks(params);
  }

  dashboardSnapshot(params) {
    return this.dashboard.dashboardSnapshot(params);
  }

  async handleDashboard(request, workspaceId, subParts) {
    return this.dashboard.handleDashboard(request, workspaceId, subParts);
  }

  async handleDashboardShell(request, workspaceId) {
    return this.dashboard.handleDashboardShell(request, workspaceId);
  }

  async handleDashboardAppJs(request) {
    return this.dashboard.handleDashboardAppJs(request);
  }

  async handleDashboardAppCss(request) {
    return this.dashboard.handleDashboardAppCss(request);
  }

  async handleDashboardLogin(request, workspaceId) {
    return this.dashboard.handleDashboardLogin(request, workspaceId);
  }

  async handleDashboardLogout(request, workspaceId) {
    return this.dashboard.handleDashboardLogout(request, workspaceId);
  }

  async handleDashboardApi(request, subParts) {
    return this.dashboard.handleDashboardApi(request, subParts);
  }

  async handleHubDashboardRelay(request) {
    return this.dashboard.handleHubDashboardRelay(request);
  }

  async handleHubDashboard(request, subParts) {
    return this.dashboard.handleHubDashboard(request, subParts);
  }

  async handleHubDashboardShell(request) {
    return this.dashboard.handleHubDashboardShell(request);
  }

  async handleHubDashboardAppJs(request) {
    return this.dashboard.handleHubDashboardAppJs(request);
  }

  async handleHubDashboardAppCss(request) {
    return this.dashboard.handleHubDashboardAppCss(request);
  }

  async handleHubDashboardLogin(request) {
    return this.dashboard.handleHubDashboardLogin(request);
  }

  async handleHubDashboardLogout(request) {
    return this.dashboard.handleHubDashboardLogout(request);
  }

  async handleHubDashboardApi(request, subParts) {
    return this.dashboard.handleHubDashboardApi(request, subParts);
  }

  async createDashboardSession() {
    return this.dashboard.createDashboardSession();
  }

  async verifyDashboardSession(raw) {
    return this.dashboard.verifyDashboardSession(raw);
  }

  async revokeDashboardSession(raw) {
    return this.dashboard.revokeDashboardSession(raw);
  }

  async dashboardSetGuidance(request) {
    return this.dashboard.dashboardSetGuidance(request);
  }

  async dashboardSetLimits(request) {
    return this.dashboard.dashboardSetLimits(request);
  }

  async getHubBrowserSettings() {
    return this.dashboard.getHubBrowserSettings();
  }

  async dashboardSetBrowserSettings(request) {
    return this.dashboard.dashboardSetBrowserSettings(request);
  }

  async dashboardAck(request) {
    return this.dashboard.dashboardAck(request);
  }

  async dashboardDiscard(request) {
    return this.dashboard.dashboardDiscard(request);
  }

  async dashboardDiscardTask(request) {
    return this.dashboard.dashboardDiscardTask(request);
  }

  async dashboardCompleteTask(request) {
    return this.dashboard.dashboardCompleteTask(request);
  }

  async dashboardContinueTask(request) {
    return this.dashboard.dashboardContinueTask(request);
  }

  async dashboardStartTask(request) {
    return this.dashboard.dashboardStartTask(request);
  }

  async dashboardSetHubBrowserSettings(request) {
    return this.dashboard.dashboardSetHubBrowserSettings(request);
  }

  async hubDashboardWorkspaces() {
    return this.dashboard.hubDashboardWorkspaces();
  }

  async hubDashboardRelay(workspaceId, opName, request) {
    return this.dashboard.hubDashboardRelay(workspaceId, opName, request);
  }

  async dashboardApiDispatch(name, method, request, url) {
    return this.dashboard.dashboardApiDispatch(name, method, request, url);
  }

  // ======================= /local : CLI-facing HTTP =======================

  async handleLocalRoute(request, token) {
    return this.transport.handleLocalRoute(request, token);
  }

  /** Ad-hoc cleanup of one message by id, either direction — for manually
   *  clearing test/abandoned entries found via `gpt-worker queue`.
   *  Refuses messages belonging to active tasks to keep protocol state consistent;
   *  callers must use localDiscardTask() instead. */
  localDiscard(body) {
    const res = this.protocol.localDiscard(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  /** Marks every not-yet-acked message for a task_id as acked, without
   *  requiring a matching submit_plan. Used when `gpt-worker task --force`
   *  replaces an unfinished task — otherwise the abandoned control messages
   *  would sit in the queue forever. */
  localDiscardTask(body) {
    const res = this.protocol.localDiscardTask(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  localStartTask(body) {
    const res = this.protocol.localStartTask(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  localReportTask(body) {
    const res = this.protocol.localReportTask(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  localMigrateLegacyState(body) {
    const res = this.protocol.localMigrateLegacyState(body);
    if (res && res.migrated) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  // Thin delegates onto the admin/settings/registry domain (bridge-admin.js)
  // — see that module's own header for the capability/dependency matrix
  // this extraction follows. Method names, argument shapes, and return
  // values are unchanged from before the extraction.

  localSettingsGet() {
    return this.admin.localSettingsGet();
  }

  localSettingsSet(body) {
    const res = this.admin.localSettingsSet(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("settings");
    }
    return res;
  }

  localBrowserSettingsGet() {
    return this.admin.localBrowserSettingsGet();
  }

  localBrowserSettingsSet(body) {
    const res = this.admin.localBrowserSettingsSet(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("settings");
    }
    return res;
  }

  localGuidanceSet(body) {
    const res = this.admin.localGuidanceSet(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("settings");
    }
    return res;
  }

  localGuidanceClear() {
    const res = this.admin.localGuidanceClear();
    if (res && !res.error) {
      this.notifyDashboardInvalidation("settings");
    }
    return res;
  }

  setSetting(key, value) {
    return this.admin.setSetting(key, value);
  }

  /** This workspace's configured `body` size cap, or the default if unset
   *  or the stored value is no longer a valid integer in range (covers a
   *  never-configured workspace and a stale value from a lowered ceiling). */
  maxBodyBytes() {
    return this.admin.maxBodyBytes();
  }

  /** The envelope around `maxBodyBytes()` — used wherever a request carrying
   *  a message body is size-checked before that body is parsed out and
   *  checked on its own. */
  maxRequestBytes() {
    return this.admin.maxRequestBytes();
  }

  localMaxBodyBytesGet() {
    return this.admin.localMaxBodyBytesGet();
  }

  localMaxBodyBytesSet(body) {
    const res = this.admin.localMaxBodyBytesSet(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("settings");
    }
    return res;
  }

  /** Debug/inspection: every not-yet-acked message in both directions, oldest
   *  first, with the body truncated for display. Not used by the normal
   *  task/wait/report loop — this is what `gpt-worker queue` calls. */
  localList(body) {
    return this.protocol.localList(body);
  }

  localEnqueue(body) {
    const res = this.protocol.localEnqueue(body);
    if (res && !res.error && !res.idempotent) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  async localPoll(body) {
    return this.protocol.localPoll(body);
  }

  localAck(body) {
    const res = this.protocol.localAck(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  localCompleteTask(body) {
    const res = this.protocol.localCompleteTask(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  localContinueTask(body) {
    const res = this.protocol.localContinueTask(body);
    if (res && !res.error) {
      this.notifyDashboardInvalidation("activity");
    }
    return res;
  }

  localStatus() {
    return this.transport.localStatus();
  }

  // ======================= maintenance =======================

  async alarm() {
    const cutoff = Date.now() - RETENTION_MS;
    const msgsRes = this.sql.exec(`DELETE FROM msgs WHERE state = 'acked' AND created_at < ?`, cutoff);
    const msgsChanges = typeof msgsRes?.rowsWritten === "number"
      ? msgsRes.rowsWritten
      : (this.sql.exec(`SELECT changes() AS n`).toArray()[0]?.n || 0);

    const taskCutoff = Date.now() - TASK_RETENTION_MS;
    const tasksRes = this.sql.exec(`DELETE FROM tasks WHERE protocol_state IN ('DONE', 'BLOCKED') AND updated_at < ?`, taskCutoff);
    const tasksChanges = typeof tasksRes?.rowsWritten === "number"
      ? tasksRes.rowsWritten
      : (this.sql.exec(`SELECT changes() AS n`).toArray()[0]?.n || 0);

    if (msgsChanges > 0 || tasksChanges > 0) {
      this.notifyDashboardInvalidation("activity");
    }

    const now = Date.now();
    this.oauth.cleanupExpiredOAuthState(now);
    this.dashboard.cleanupExpiredDashboardSessions(now);
    await this.ctx.storage.setAlarm(Date.now() + ALARM_INTERVAL_MS);
  }
}
